import { describe, expect, test } from 'bun:test'
import { buildClobHmacSignature } from '../services/PolymarketService'

// CLOB L2 auth. If this signature does not byte-match Polymarket's reference
// implementation, every authenticated request 401s — so these vectors were
// generated by running Polymarket's OWN code (py-clob-client 0.34.6,
// signing/hmac.py::build_hmac_signature) rather than derived from our own logic:
//
//   >>> from py_clob_client.signing.hmac import build_hmac_signature
//   >>> build_hmac_signature(SECRET, "1718000000", "POST", "/order", '{"a":1}')
//
// The previous implementation keyed the HMAC with the raw secret STRING and
// emitted standard base64; the reference base64URL-DECODES the secret to raw
// bytes and base64URL-encodes the digest. Both differences break auth.
const SECRET = 'TXlTdXBlclNlY3JldEtleUZvclRlc3RpbmcxMjM0NTY3ODk='

describe('CLOB L2 HMAC matches Polymarket reference vectors', () => {
	test('POST with a body', () => {
		expect(buildClobHmacSignature(SECRET, '1718000000', 'POST', '/order', '{"a":1}')).toBe(
			'scRg4XkClA6l95Pd9hxFOpiDfhP4ce6_rUWQo0WRQL8=',
		)
	})

	test('GET with no body', () => {
		expect(buildClobHmacSignature(SECRET, '1718000000', 'GET', '/orders')).toBe(
			'pQJGuWoe_gXxbU66Jky5vUSHtI2l2BUOYi-QWbcEDDI=',
		)
	})

	test('output is base64url, not standard base64', () => {
		// base64url uses - and _ instead of + and /. Both fixtures above contain a
		// '_' or '-', which standard base64 could never produce — that is exactly
		// the bug this guards against.
		const sig = buildClobHmacSignature(SECRET, '1718000000', 'GET', '/orders')
		expect(sig).not.toMatch(/[+/]/)
		expect(sig).toMatch(/[-_]/)
	})

	test("'=' padding is preserved (Node's base64url strips it, Python keeps it)", () => {
		// Node's digest('base64url') would drop the trailing '=' that Python's
		// urlsafe_b64encode emits. The server compares strings, so one missing
		// character fails auth — an easy regression to reintroduce.
		expect(buildClobHmacSignature(SECRET, '1718000000', 'GET', '/orders')).toEndWith('=')
	})

	test('the raw-secret keying regression stays fixed', () => {
		// Keying with the secret STRING (the old behaviour) produces a different
		// signature than keying with its decoded bytes. Pin the difference so the
		// old approach cannot silently return.
		const crypto = require('crypto')
		const wrong = crypto
			.createHmac('sha256', SECRET)
			.update('1718000000' + 'GET' + '/orders')
			.digest('base64')
		expect(buildClobHmacSignature(SECRET, '1718000000', 'GET', '/orders')).not.toBe(wrong)
	})
})
