export { Welcome } from './Welcome'
export { Home } from './Home'
export { Swap } from './Swap'
export { Wallet } from './Wallet'
export { Portfolio } from './Portfolio'
export { History } from './History'
export { Settings } from './Settings'
