import {
	boolean,
	integer,
	json,
	pgTable,
	real,
	serial,
	timestamp,
	varchar,
} from 'drizzle-orm/pg-core'

export const snipeOrders = pgTable('snipe_orders', {
	id: serial('id').primaryKey(),
	userId: integer('user_id').notNull(),
	walletId: integer('wallet_id').notNull(),
	tokenMint: varchar('token_mint', { length: 64 }),
	tokenName: varchar('token_name', { length: 100 }),
	tokenSymbol: varchar('token_symbol', { length: 20 }),
	platform: varchar('platform', { length: 30 }).default('any'),
	solAmount: real('sol_amount').notNull(),
	slippageBps: integer('slippage_bps').default(1000),
	mode: varchar('mode', { length: 20 }).default('instant'),
	useJito: boolean('use_jito').default(true),
	jitoTipLamports: integer('jito_tip_lamports').default(10_000_000),
	status: varchar('status', { length: 20 }).default('pending'),
	statusMessage: varchar('status_message', { length: 255 }),
	minLiquiditySol: real('min_liquidity_sol'),
	maxPriceSol: real('max_price_sol'),
	requireSocials: boolean('require_socials').default(false),
	minQualityScore: real('min_quality_score'),
	executedAt: timestamp('executed_at'),
	txSignature: varchar('tx_signature', { length: 128 }),
	bundleId: varchar('bundle_id', { length: 128 }),
	solSpent: real('sol_spent'),
	tokensReceived: varchar('tokens_received', { length: 78 }),
	executionPrice: real('execution_price'),
	executionTimeMs: real('execution_time_ms'),
	slot: integer('slot'),
	retries: integer('retries').default(0),
	errorMessage: varchar('error_message', { length: 500 }),
	expiresAt: timestamp('expires_at'),
	createdAt: timestamp('created_at').defaultNow(),
	updatedAt: timestamp('updated_at').defaultNow(),
})

export const snipeConfigs = pgTable('snipe_configs', {
	id: serial('id').primaryKey(),
	userId: integer('user_id').notNull().unique(),
	quickAmounts: json('quick_amounts').default([0.1, 0.5, 1.0, 5.0]),
	defaultSolAmount: real('default_sol_amount').default(0.5),
	defaultSlippageBps: integer('default_slippage_bps').default(1000),
	defaultMode: varchar('default_mode', { length: 20 }).default('instant'),
	useJito: boolean('use_jito').default(true),
	defaultJitoTip: integer('default_jito_tip').default(10_000_000),
	autoSnipeEnabled: boolean('auto_snipe_enabled').default(false),
	autoSnipeMinLiquidity: real('auto_snipe_min_liquidity').default(5.0),
	autoSnipeMaxLiquidity: real('auto_snipe_max_liquidity').default(100.0),
	autoSnipeRequireSocials: boolean('auto_snipe_require_socials').default(false),
	autoSnipePlatforms: json('auto_snipe_platforms').default(['pump_fun', 'raydium']),
	autoSnipeDailyBudget: real('auto_snipe_daily_budget').default(10.0),
	autoSnipeUsedToday: real('auto_snipe_used_today').default(0.0),
	honeypotCheck: boolean('honeypot_check').default(true),
	authorityCheck: boolean('authority_check').default(true),
	blacklistCheck: boolean('blacklist_check').default(true),
	notifyOnLaunch: boolean('notify_on_launch').default(true),
	notifyOnExecution: boolean('notify_on_execution').default(true),
	notifyOnFailure: boolean('notify_on_failure').default(true),
	createdAt: timestamp('created_at').defaultNow(),
	updatedAt: timestamp('updated_at').defaultNow(),
})

export const snipeHistory = pgTable('snipe_history', {
	id: serial('id').primaryKey(),
	userId: integer('user_id').notNull(),
	snipeOrderId: integer('snipe_order_id'),
	tokenMint: varchar('token_mint', { length: 64 }).notNull(),
	tokenName: varchar('token_name', { length: 100 }),
	tokenSymbol: varchar('token_symbol', { length: 20 }),
	platform: varchar('platform', { length: 30 }).notNull(),
	solSpent: real('sol_spent').notNull(),
	tokensReceived: varchar('tokens_received', { length: 78 }).notNull(),
	entryPrice: real('entry_price').notNull(),
	executionTimeMs: real('execution_time_ms'),
	currentPrice: real('current_price'),
	currentValueSol: real('current_value_sol'),
	pnlSol: real('pnl_sol'),
	pnlPercent: real('pnl_percent'),
	highestPrice: real('highest_price'),
	lowestPrice: real('lowest_price'),
	isSold: boolean('is_sold').default(false),
	soldAt: timestamp('sold_at'),
	exitPrice: real('exit_price'),
	solReceived: real('sol_received'),
	realizedPnlSol: real('realized_pnl_sol'),
	realizedPnlPercent: real('realized_pnl_percent'),
	snipedAt: timestamp('sniped_at').defaultNow(),
	updatedAt: timestamp('updated_at').defaultNow(),
})

export const watchedTokens = pgTable('watched_tokens', {
	id: serial('id').primaryKey(),
	userId: integer('user_id').notNull(),
	tokenMint: varchar('token_mint', { length: 64 }).notNull(),
	tokenName: varchar('token_name', { length: 100 }),
	tokenSymbol: varchar('token_symbol', { length: 20 }),
	platform: varchar('platform', { length: 30 }).notNull(),
	snipeOnMigration: boolean('snipe_on_migration').default(true),
	snipeSolAmount: real('snipe_sol_amount').default(0.5),
	alertOnProgress: boolean('alert_on_progress').default(true),
	progressPercent: real('progress_percent').default(0),
	bondingCurve: varchar('bonding_curve', { length: 64 }),
	isActive: boolean('is_active').default(true),
	migrated: boolean('migrated').default(false),
	migratedAt: timestamp('migrated_at'),
	sniped: boolean('sniped').default(false),
	createdAt: timestamp('created_at').defaultNow(),
	updatedAt: timestamp('updated_at').defaultNow(),
})

export const autoSnipeRules = pgTable('auto_snipe_rules', {
	id: serial('id').primaryKey(),
	userId: integer('user_id').notNull(),
	walletId: integer('wallet_id').notNull(),
	name: varchar('name', { length: 50 }).notNull(),
	isActive: boolean('is_active').default(true),
	platforms: json('platforms').default(['pump_fun', 'raydium']),
	minLiquiditySol: real('min_liquidity_sol'),
	maxLiquiditySol: real('max_liquidity_sol'),
	minQualityScore: real('min_quality_score'),
	requireSocials: boolean('require_socials').default(false),
	nameMustContain: json('name_must_contain').default([]),
	nameMustNotContain: json('name_must_not_contain').default([]),
	creatorWhitelist: json('creator_whitelist').default([]),
	creatorBlacklist: json('creator_blacklist').default([]),
	solAmount: real('sol_amount').notNull(),
	slippageBps: integer('slippage_bps').default(1000),
	useJito: boolean('use_jito').default(true),
	jitoTip: integer('jito_tip').default(10_000_000),
	maxSnipesPerDay: integer('max_snipes_per_day').default(10),
	maxSolPerDay: real('max_sol_per_day').default(5.0),
	snipesToday: integer('snipes_today').default(0),
	solSpentToday: real('sol_spent_today').default(0),
	lastResetDate: varchar('last_reset_date', { length: 10 }),
	totalSnipes: integer('total_snipes').default(0),
	successfulSnipes: integer('successful_snipes').default(0),
	totalSolSpent: real('total_sol_spent').default(0),
	totalPnlSol: real('total_pnl_sol').default(0),
	createdAt: timestamp('created_at').defaultNow(),
	updatedAt: timestamp('updated_at').defaultNow(),
})

export type SnipeOrder = typeof snipeOrders.$inferSelect
export type NewSnipeOrder = typeof snipeOrders.$inferInsert
export type SnipeConfig = typeof snipeConfigs.$inferSelect
export type NewSnipeConfig = typeof snipeConfigs.$inferInsert
export type SnipeHistoryEntry = typeof snipeHistory.$inferSelect
export type NewSnipeHistoryEntry = typeof snipeHistory.$inferInsert
export type WatchedToken = typeof watchedTokens.$inferSelect
export type NewWatchedToken = typeof watchedTokens.$inferInsert
export type AutoSnipeRule = typeof autoSnipeRules.$inferSelect
export type NewAutoSnipeRule = typeof autoSnipeRules.$inferInsert
