export { default as Hero } from './Hero'
export { default as Features } from './Features'
export { default as PlatformDemos } from './PlatformDemos'
export { default as HowItWorks } from './HowItWorks'
export { default as CTA } from './CTA'
export { default as SocialProof } from './SocialProof'
export { default as FAQ } from './FAQ'
export { default as Footer } from './Footer'
