/**
 * ENSv2 Sepolia deployment addresses — canonical source.
 *
 * Verified 2026-09-25 against the auto-generated deployment table in
 * ensdomains/contracts-v2 @ sepolia-deployment-2026-09-15:
 *   contracts/docs/addresses/sepolia.md
 * (network: Sepolia, chain ID 11155111, deployed 2026-09-15T09:46:38Z,
 *  generated by `bun run docs:addresses`).
 *
 * ⚠️ The previous 2026-07-31 deployment set is ARCHIVED (release notes:
 * "no longer wired to v1"; its ETHRegistry "keeps its old events but is no
 * longer resolved against"). Do not use the old addresses.
 *
 * Operational note: resolve v2 names against the fresh UniversalResolverV2
 * (0x5d25…) directly — its ROOT_REGISTRY is immutable and `resolve()` is a
 * view, so the implementation address answers directly. The
 * UpgradableUniversalResolverProxy (0xeEeE…) is the shared deterministic
 * proxy; the fresh deployment also ships ManagedUniversalResolverProxy.
 */
import type { Address } from 'viem'

export const SEPOLIA_CHAIN_ID = 11155111 as const

export const ENSV2_SEPOLIA = {
	/** Fresh-deployment Universal Resolver — the client entrypoint for v2 names. */
	universalResolverV2: '0x5d25c1d6acbb71b7a28aa7899618a3412a8303e3' as Address,
	/** Deploys UUPS resolver proxies: deployProxy(implementation, salt, data). */
	verifiableFactory: '0x9e726eb570beb6bceb495ab8cda7df517d4e841c' as Address,
	/** Resolver implementation (UUPS) — proxy via the factory, then initialize(). */
	permissionedResolverImpl: '0x14f09fd05d4585759e54844dc9b00147131cf243' as Address,
	/** .eth registrar — commit/reveal + ERC20 payment. */
	ethRegistrar: '0xabe76f6c8dfced81aa5a2bb8034202a7136b94ca' as Address,
	/** Registry that owns .eth names; getSubregistry("suwappu") → our registry. */
	ethRegistry: '0x657ea849311d3d5823348dded7c2aaafb3ede09e' as Address,
	/** Root registry (name registrations live under it). */
	rootRegistry: '0x9703dbd26dab89504490994138cf2c575251a9ce' as Address,
	/** ERC20 the v2 ETHRegistrar accepts for registration fees. */
	mockUSDC: '0x16f95d91dba7da3aca778ec053df0ff6c6a8aa8e' as Address,
	/**
	 * Public proxy entrypoint — the shared deterministic proxy. For v2 names
	 * on the fresh deployment, prefer universalResolverV2 directly.
	 */
	publicProxyRepointed: '0xeEeEEEeE14D718C2B47D9923Deab1335E144EeEe' as Address,
	/** Managed proxy for the fresh deployment's resolver. */
	managedUniversalResolverProxy: '0x6d80F2172CFdEc5730fE683860C33d26fC42e6F1' as Address,
	/** UniversalHelper — findExactOwner / findNearestOwner / findNearestRegistry (moved off URv2). */
	universalHelper: '0x33f571aa8a160a21b877cf6e0fb8806692b97df5' as Address,
} as const

/** Text-record keys this project uses on agent subnames. */
export const TEXT_KEYS = {
	policy: 'suwappu.policy',
	worldId: 'suwappu.worldid',
	risk: 'suwappu.risk',
	version: 'suwappu.agent-version',
} as const

/** Metadata keys the agent key itself is allowed to rewrite (owner-authorized).
 * Note: deliberately NOT in the `suwappu.*` namespace — that namespace is
 * reserved for owner-only records (policy, World ID binding, risk notes). */
export const AGENT_WRITABLE_KEYS = ['avatar', 'description', 'agent-version'] as const

export function agentSubname(agent: string, parent = 'suwappu'): string {
	return `${agent}.${parent}.eth`
}
