/**
 * ENSv2 Sepolia deployment addresses — canonical source.
 *
 * Verified 2026-09-25 against the auto-generated deployment table in
 * ensdomains/contracts-v2 @ 97a57293f3b4279d94b571e678edb53ce62638f4:
 *   contracts/docs/addresses/sepolia.md
 * (network: Sepolia, chain ID 11155111, deployed 2026-07-30T17:34:25Z,
 *  generated by `bun run docs:addresses`).
 *
 * ⚠️ Operational caveat (same source, repo README): the public
 * UpgradableUniversalResolverProxy entrypoint (0xeEeE…) is TEMPORARILY
 * repointed at the *previous* deployment's UniversalResolverV2 so v1 names
 * keep resolving while the fresh deployment's v1 mirror is wired up.
 * For v2 names on the fresh deployment, call the fresh
 * UniversalResolverV2 (0x4a18…) directly — its ROOT_REGISTRY is immutable
 * and `resolve()` is a view, so the implementation address answers directly.
 */
import type { Address } from 'viem'

export const SEPOLIA_CHAIN_ID = 11155111 as const

export const ENSV2_SEPOLIA = {
	/** Fresh-deployment Universal Resolver — the client entrypoint for v2 names. */
	universalResolverV2: '0x4a1817d13e9cf196f471725176355c1234b63c70' as Address,
	/** Deploys UUPS resolver proxies: deployProxy(implementation, salt, data). */
	verifiableFactory: '0x10dc6333cdfe1fcef624c6e0a8221b91804cd7ef' as Address,
	/** Resolver implementation (UUPS) — proxy via the factory, then initialize(). */
	permissionedResolverImpl: '0x9eae5c2730a7dd16bdd1dee6421a1b91e3b0365e' as Address,
	/** .eth registrar — commit/reveal + ERC20 payment. */
	ethRegistrar: '0xa88553f454b77203b0d036a05c894d555eaaa2cc' as Address,
	/** Registry that owns .eth names; getSubregistry("suwappu") → our registry. */
	ethRegistry: '0xbdc85dd5b15d7ecb354cd7cb6f2c50b4f2c4f0e2' as Address,
	/** Root registry (name registrations live under it). */
	rootRegistry: '0x8115186e8f2e0b0281e86ab91f0f48ba90364354' as Address,
	/** ERC20 the v2 ETHRegistrar accepts for registration fees. */
	mockUSDC: '0x768f42455a2d082e23ceef7d51e5787c82d67a39' as Address,
	/**
	 * Public proxy entrypoint — currently repointed to the PREVIOUS
	 * deployment (v1 names). Do NOT use for v2 names; use universalResolverV2.
	 */
	publicProxyRepointed: '0xeEeEEEeE14D718C2B47D9923Deab1335E144EeEe' as Address,
} as const

/** Text-record keys this project uses on agent subnames. */
export const TEXT_KEYS = {
	policy: 'suwappu.policy',
	worldId: 'suwappu.worldid',
	risk: 'suwappu.risk',
	version: 'suwappu.agent-version',
} as const

/** Metadata keys the agent key itself is allowed to rewrite (owner-authorized).
 * Note: deliberately NOT in the `suwappu.*` namespace — that namespace is
 * reserved for owner-only records (policy, World ID binding, risk notes). */
export const AGENT_WRITABLE_KEYS = ['avatar', 'description', 'agent-version'] as const

export function agentSubname(agent: string, parent = 'suwappu'): string {
	return `${agent}.${parent}.eth`
}
