'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, ArrowSquareOut, ChartBar, Database, Gauge, MagnifyingGlass, Question, ShieldCheck, Users, Wallet } from '@phosphor-icons/react';
import styles from './signals.module.css';

type Overview = { total_transactions?:number; tx_5m?:number; wallets_1h?:number; mints_1h?:number; last_ingest?:string; errors_1h?:number };
type ComponentScore = { points:number; max:number; why:string };
type TokenRow = { mint:string; score:number; label:string; tx_5m:number; tx_30m:number; buyers_5m:number; sellers_5m:number; repeat_buyers_5m:number; last_seen?:string; components:Record<string,ComponentScore>; warning:string };
type WalletRow = { wallet:string; mints_24h:number; transactions_24h:number; receive_events:number; send_events:number; label:string; plain_english:string; last_seen?:string };
type ActivityRow = { signature:string; source_program:string; slot:number; fee_payer:string; success:boolean; fee_lamports:number; compute_units:number; instruction_count:number; token_delta_count:number; ingested_at:string; what_it_means:string };
type EvidenceRow = { signature:string; ingested_at:string; fee_payer:string; owner:string; delta:string; decimals:number; direction:string };
type View = 'overview'|'tokens'|'wallets'|'evidence'|'methodology';

const short=(s?:string)=>!s?'—':s.length>18?`${s.slice(0,8)}…${s.slice(-6)}`:s;
const compact=(v?:number)=>new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(Number(v||0));
const ago=(v?:string)=>{if(!v)return'—';const d=Math.max(0,Date.now()-new Date(v).getTime());if(d<60_000)return`${Math.floor(d/1000)}s ago`;if(d<3_600_000)return`${Math.floor(d/60_000)}m ago`;return`${Math.floor(d/3_600_000)}h ago`};

async function getJSON<T>(path:string):Promise<T>{const r=await fetch(`/api/signals${path}`,{credentials:'include',cache:'no-store'});if(r.status===401)throw new Error('Your session expired. Refresh and sign in again.');if(!r.ok)throw new Error('Signal data is temporarily unavailable.');return r.json()}

export default function SignalIntelligencePage(){
 const [view,setView]=useState<View>('overview');const[query,setQuery]=useState('');const[overview,setOverview]=useState<Overview>({});const[tokens,setTokens]=useState<TokenRow[]>([]);const[wallets,setWallets]=useState<WalletRow[]>([]);const[activity,setActivity]=useState<ActivityRow[]>([]);const[selected,setSelected]=useState<TokenRow|null>(null);const[evidence,setEvidence]=useState<EvidenceRow[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
 useEffect(()=>{let alive=true;const load=async()=>{try{const[o,t,w,a]=await Promise.all([getJSON<Overview>('/overview'),getJSON<TokenRow[]>('/tokens?limit=50'),getJSON<WalletRow[]>('/wallets?limit=50'),getJSON<ActivityRow[]>('/activity?limit=50')]);if(!alive)return;setOverview(o);setTokens(t);setWallets(w);setActivity(a);setError(null)}catch(e){if(alive)setError(e instanceof Error?e.message:'Signal data is temporarily unavailable.')}finally{if(alive)setLoading(false)}};void load();const id=setInterval(load,20_000);return()=>{alive=false;clearInterval(id)}},[]);
 useEffect(()=>{if(!selected)return;getJSON<EvidenceRow[]>(`/evidence/${selected.mint}`).then(setEvidence).catch(()=>setEvidence([]))},[selected]);
 const visibleTokens=useMemo(()=>tokens.filter(x=>x.mint.toLowerCase().includes(query.toLowerCase())),[tokens,query]);const visibleWallets=useMemo(()=>wallets.filter(x=>x.wallet.toLowerCase().includes(query.toLowerCase())),[wallets,query]);
 const nav:[View,string,React.ReactNode][]=[['overview','Overview',<Gauge size={18}/>],['tokens','Token signals',<ChartBar size={18}/>],['wallets','Wallet behavior',<Users size={18}/>],['evidence','Chain evidence',<Database size={18}/>],['methodology','Methodology',<Question size={18}/>]];
 return <div className={styles.app}>
  <header className={styles.topbar}><div className={styles.brand}><Link href="/" className={styles.wordmark}>suwappu</Link><span>/</span><strong>Signal Intelligence</strong></div><div className={styles.search}><MagnifyingGlass size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search mint or wallet"/></div><div className={styles.status}><span className={error?styles.statusWarn:styles.statusDot}/><span>{error?'Data delayed':`Live · ${ago(overview.last_ingest)}`}</span></div></header>
  <div className={styles.body}><aside className={styles.sidebar}><div className={styles.sideLabel}>Research workspace</div>{nav.map(([id,label,icon])=><button key={id} onClick={()=>setView(id)} className={view===id?styles.navActive:styles.nav}>{icon}<span>{label}</span></button>)}<div className={styles.sideRule}/><Link href="/dashboard" className={styles.nav}><Wallet size={18}/><span>Account dashboard</span></Link><div className={styles.readOnly}><ShieldCheck size={18}/><div><b>Read-only workspace</b><span>No trading permissions</span></div></div></aside>
  <main className={styles.main}>{error&&<div className={styles.alert}>{error}</div>}{view==='overview'&&<OverviewView loading={loading} overview={overview} tokens={tokens.slice(0,6)} wallets={wallets.slice(0,6)} onSelect={setSelected} onViewTokens={()=>setView('tokens')}/>} {view==='tokens'&&<TokensView rows={visibleTokens} onSelect={setSelected}/>} {view==='wallets'&&<WalletsView rows={visibleWallets}/>} {view==='evidence'&&<EvidenceView rows={activity}/>} {view==='methodology'&&<Methodology/>}</main></div>{selected&&<Drawer token={selected} rows={evidence} close={()=>setSelected(null)}/>}</div>
}

function Head({kicker,title,copy}:{kicker:string;title:string;copy:string}){return <div className={styles.head}><div>{kicker}</div><h1>{title}</h1><p>{copy}</p></div>}
function Card({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={`${styles.card} ${className}`}>{children}</section>}
function Kpi({label,value,note,icon}:{label:string;value:string;note:string;icon:React.ReactNode}){return <Card className={styles.kpi}><div className={styles.kpiTop}>{icon}<span>{label}</span></div><strong>{value}</strong><small>{note}</small></Card>}
function OverviewView({loading,overview,tokens,wallets,onSelect,onViewTokens}:{loading:boolean;overview:Overview;tokens:TokenRow[];wallets:WalletRow[];onSelect:(t:TokenRow)=>void;onViewTokens:()=>void}){return <><Head kicker="Live intelligence" title="What is happening on-chain?" copy="A simple view of the Pump/PumpSwap activity Suwappu can prove from the ledger. Every signal is clickable and traceable to transactions."/><div className={styles.kpis}><Kpi label="Transactions observed" value={loading?'—':compact(overview.total_transactions)} note="Canonical chain events" icon={<Database/>}/><Kpi label="Activity · 5 min" value={loading?'—':compact(overview.tx_5m)} note="Fresh transaction flow" icon={<Database/>}/><Kpi label="Active wallets · 1h" value={loading?'—':compact(overview.wallets_1h)} note="Distinct fee payers" icon={<Users/>}/><Kpi label="Token mints · 1h" value={loading?'—':compact(overview.mints_1h)} note="Mints with balance changes" icon={<ChartBar/>}/></div><div className={styles.twoCol}><Card><div className={styles.cardHead}><div><b>Tokens attracting attention</b><span>Observable flow only — not predicted return.</span></div><button onClick={onViewTokens}>View all <ArrowRight/></button></div><div>{tokens.length?tokens.map(t=><button key={t.mint} onClick={()=>onSelect(t)} className={styles.listRow}><div><b className={styles.mono}>{short(t.mint)}</b><span>{t.buyers_5m} receiving wallets · {t.tx_5m} tx / 5m</span></div><div className={styles.score}><strong>{Math.round(t.score)}</strong><span>{t.label}</span></div></button>):<Empty/>}</div></Card><Card><div className={styles.cardHead}><div><b>Repeat participants</b><span>Wallets appearing across multiple mints.</span></div></div>{wallets.length?wallets.map(w=><div key={w.wallet} className={styles.walletMini}><b className={styles.mono}>{short(w.wallet)}</b><span>{w.mints_24h} mints · {w.transactions_24h} observed transactions</span><em>{w.label}</em></div>):<Empty/>}</Card></div></>}
function TokensView({rows,onSelect}:{rows:TokenRow[];onSelect:(t:TokenRow)=>void}){return <><Head kicker="Token research" title="Where is activity clustering?" copy="The score is decomposed into visible ingredients. Click any token to see why it scored that way and which transactions support it."/><Card><div className={styles.tableWrap}><table><thead><tr><th>Token</th><th>Plain-English signal</th><th>5m tx</th><th>Buyers</th><th>Sellers</th><th>Repeat</th><th>Score</th></tr></thead><tbody>{rows.map(t=><tr key={t.mint} onClick={()=>onSelect(t)}><td className={styles.mono}>{short(t.mint)}</td><td><span className={styles.pill}>{t.label}</span></td><td>{t.tx_5m}</td><td>{t.buyers_5m}</td><td>{t.sellers_5m}</td><td>{t.repeat_buyers_5m}</td><td><b>{Math.round(t.score)}/100</b></td></tr>)}</tbody></table></div></Card></>}
function WalletsView({rows}:{rows:WalletRow[]}){return <><Head kicker="Participant research" title="Which wallets keep showing up?" copy="Labels describe behavior we can observe on-chain. They do not identify people and they do not claim a wallet is profitable or informed."/><div className={styles.walletGrid}>{rows.map(w=><Card key={w.wallet} className={styles.walletCard}><div className={styles.walletTop}><div><b className={styles.mono}>{short(w.wallet)}</b><h3>{w.label}</h3></div><span className={styles.pill}>{w.mints_24h} mints</span></div><p>{w.plain_english}</p><div className={styles.walletStats}><span><b>{w.receive_events}</b> receive events</span><span><b>{w.send_events}</b> send events</span><span>seen {ago(w.last_seen)}</span></div></Card>)}</div></>}
function EvidenceView({rows}:{rows:ActivityRow[]}){return <><Head kicker="Audit trail" title="What actually happened on-chain?" copy="This is the evidence layer underneath every summary. It keeps the product explainable for operators, researchers, and compliance reviewers."/><Card>{rows.map(x=><div key={x.signature} className={styles.evidenceRow}><div className={styles.evidenceTop}><b className={styles.mono}>{short(x.signature)}</b><span>{ago(x.ingested_at)} · slot {x.slot}</span></div><p>{x.what_it_means}</p><div className={styles.tags}><span>{x.source_program}</span><span>{x.instruction_count} instructions</span><span>{x.token_delta_count} token changes</span><span>{x.success?'confirmed':'failed'}</span><a href={`https://solscan.io/tx/${x.signature}`} target="_blank" rel="noreferrer">Solscan <ArrowSquareOut/></a></div></div>)}</Card></>}
function Methodology(){const xs=[['Flow acceleration','40 points','Is transaction activity arriving faster than the token’s recent baseline?'],['Buyer breadth','30 points','How many distinct wallets are receiving the token?'],['Buy / sell balance','20 points','Is observed receiving breadth stronger than sending breadth?'],['Repeat participants','10 points','Are wallets that repeatedly touch multiple mints appearing here?']];return <><Head kicker="Explainability" title="How Suwappu turns chain data into a signal" copy="There is no hidden model in this score. It is a transparent attention measure built from ledger behavior and designed to be audited."/><div className={styles.methodGrid}>{xs.map(([a,b,c])=><Card key={a} className={styles.method}><div><b>{a}</b><span>{b}</span></div><p>{c}</p></Card>)}</div><Card className={styles.caveat}><ShieldCheck size={24}/><div><b>What the current score does not mean</b><p>It is not a price prediction, trade recommendation, or proof that a wallet is profitable. It is a structured summary of observable attention that can later feed validated research models.</p></div></Card></>}
function Drawer({token,rows,close}:{token:TokenRow;rows:EvidenceRow[];close:()=>void}){return <div className={styles.scrim} onMouseDown={e=>e.currentTarget===e.target&&close()}><aside className={styles.drawer}><div className={styles.drawerHead}><div><span>Signal explanation</span><b className={styles.mono}>{short(token.mint)}</b></div><button onClick={close}>Close</button></div><div className={styles.drawerBody}><div className={styles.heroScore}><strong>{Math.round(token.score)}</strong><div><b>{token.label}</b><span>0–100 observable attention score</span></div></div><div className={styles.components}>{Object.entries(token.components).map(([name,c])=><div key={name} className={styles.component}><div><b>{name}</b><span>{c.points}/{c.max}</span></div><div className={styles.bar}><i style={{width:`${Math.min(100,c.points/c.max*100)}%`}}/></div><p>{c.why}</p></div>)}</div><h3>On-chain evidence</h3><p className={styles.muted}>Recent balance changes for this mint. These are the events behind the aggregate score.</p><div className={styles.evidenceList}>{rows.slice(0,20).map((r,i)=><div key={`${r.signature}-${i}`}><div><b className={styles.mono}>{short(r.signature)}</b><span>{ago(r.ingested_at)}</span></div><p>Wallet {short(r.owner)} {r.direction} token balance.</p><a href={`https://solscan.io/tx/${r.signature}`} target="_blank" rel="noreferrer">Inspect transaction <ArrowSquareOut/></a></div>)}</div><div className={styles.warning}>{token.warning}</div></div></aside></div>}
function Empty(){return <div className={styles.empty}>Waiting for enough on-chain activity to form a view.</div>}
