export { a2aRoutes } from './a2a'
export { adminRoutes } from './admin'
export { agentRoutes } from './agent'
export { healthRoutes } from './health'
export { publicSwapRoutes } from './publicSwap'
export { swapRoutes } from './swap'
export { webappRoutes } from './webapp'
