// THE message contract. Every layer imports these types.
//
//   dApp page (MAIN world)
//     └─ window.ethereum / window.solana   [src/inpage]
//          │  window.postMessage(InpageToContent / ContentToInpage)
//     ┌────┴────────────────────────────────────────────────────────
//   content bridge (ISOLATED world)        [src/content]
//          │  chrome.runtime port (PORT_NAME)  PortMessage
//     ┌────┴────────────────────────────────────────────────────────
//   service worker / router                [src/background]
//          │  chrome.runtime.sendMessage     PopupMessage
//     ┌────┴────────────────────────────────────────────────────────
//   popup UI                               [src/popup]
//
import type { SerializedRpcError } from "./rpc-errors";

// ── JSON-RPC envelope (EIP-1193 request shape) ────────────────────────────
export interface RpcRequest {
  /** uuid generated by the inpage provider; echoed back on the response. */
  id: string;
  method: string;
  params?: unknown[] | Record<string, unknown>;
}

export interface RpcResponse {
  id: string;
  result?: unknown;
  error?: SerializedRpcError;
}

// ── Provider events pushed dApp-ward (EIP-1193) ───────────────────────────
export type ProviderEventName =
  | "accountsChanged"
  | "chainChanged"
  | "connect"
  | "disconnect"
  | "message";

export interface ProviderEvent {
  event: ProviderEventName;
  data: unknown;
}

// ── window.postMessage envelopes (inpage <-> content) ──────────────────────
// Discriminated on `target`. `namespace` is always WALLET_NAMESPACE; the
// content bridge MUST ignore any message lacking it.
export type Chain = "eip155" | "solana";

export interface InpageToContent {
  namespace: string;
  target: "content";
  chain: Chain;
  payload: RpcRequest;
}

export interface ContentToInpage {
  namespace: string;
  target: "inpage";
  chain: Chain;
  /** Present for an RPC reply; absent for a pushed provider event. */
  payload?: RpcResponse;
  /** Present for a pushed provider event; absent for an RPC reply. */
  event?: ProviderEvent;
}

// ── content <-> background (chrome.runtime.Port) ──────────────────────────
export type PortMessage =
  | { kind: "rpc"; chain: Chain; origin: string; request: RpcRequest }
  | { kind: "rpc-result"; chain: Chain; response: RpcResponse }
  | { kind: "event"; chain: Chain; origin: string; event: ProviderEvent };

// ── popup <-> background (chrome.runtime.sendMessage) ─────────────────────
// The popup is a TRUSTED context: it can unlock the vault, resolve approvals,
// and read wallet state. Discriminated on `type`.
export type PopupRequest =
  | { type: "getState" }
  | { type: "unlock"; prfOutput: number[] } // PRF bytes from a WebAuthn get()
  | { type: "lock" }
  | { type: "createVault"; prfOutput: number[]; mnemonic?: string }
  | { type: "importVault"; prfOutput: number[]; mnemonic: string }
  | { type: "listPendingApprovals" }
  | { type: "resolveApproval"; approvalId: string; approved: boolean; result?: unknown }
  | { type: "selectAccount"; address: string }
  | { type: "switchChain"; chainId: number };

export interface WalletState {
  initialized: boolean; // a vault exists in storage.local
  unlocked: boolean; // unlocked key present in storage.session
  selectedAddress: string | null;
  selectedChainId: number;
  accounts: string[];
  pendingApprovalCount: number;
}

export type PopupResponse =
  | { ok: true; data?: unknown }
  | { ok: false; error: SerializedRpcError };

// ── Approval queue (background -> popup) ──────────────────────────────────
export type ApprovalKind = "connect" | "signMessage" | "signTypedData" | "sendTransaction";

export interface ApprovalRequest {
  id: string;
  kind: ApprovalKind;
  origin: string;
  chain: Chain;
  /** Method-specific payload (the tx object, the message, the typed data). */
  data: unknown;
  createdAt: number;
}

// ── Read-only RPC method classification (router uses this) ─────────────────
/** Methods the router can answer without an unlocked key or user approval. */
export const PUBLIC_EVM_METHODS = new Set<string>([
  "eth_chainId",
  "eth_blockNumber",
  "eth_getBalance",
  "eth_call",
  "eth_estimateGas",
  "eth_gasPrice",
  "eth_maxPriorityFeePerGas",
  "eth_feeHistory",
  "eth_getCode",
  "eth_getTransactionByHash",
  "eth_getTransactionReceipt",
  "eth_getTransactionCount",
  "eth_getBlockByNumber",
  "eth_getBlockByHash",
  "eth_getLogs",
  "net_version",
  "web3_clientVersion",
]);

/** Methods that require an explicit user approval before executing. */
export const APPROVAL_EVM_METHODS = new Set<string>([
  "eth_requestAccounts",
  "personal_sign",
  "eth_sign",
  "eth_signTypedData",
  "eth_signTypedData_v4",
  "eth_sendTransaction",
  "wallet_addEthereumChain",
  "wallet_switchEthereumChain",
]);
