#!/usr/bin/env python3
"""Suwappu Positions — live position-card renderer.

A card is drawn from REAL state only: the ticker you chose, the entry price
stamped on-chain when you minted, and the current oracle price. Nothing here
invents price history — the previous iteration of this collection drew a fake
random-walk chart, which is exactly the kind of decoration that makes a card
worthless. The hero element is the actual return between two real numbers.

The ticker universe (symbol, ERC-20 address, decimals, company name) is parsed
from bot/config/tokens.py::ROBINHOOD_EQUITIES so the collection cannot drift
from what is tradable on chain 4663.

  python3 nft/position-cards/render.py --gallery        # sample cards -> preview/
  python3 nft/position-cards/render.py --ticker NVDA --entry 100 --price 168 --rank 42
"""

import argparse
import ast
import json
import os
import re
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
TOKENS_PY = os.path.join(REPO, "bot", "config", "tokens.py")

W, H = 1000, 1250
M = 44
CX0, CX1 = M, W - M
PAD = 38
IX0, IX1 = CX0 + PAD, CX1 - PAD


def load_registry() -> dict:
    src = open(TOKENS_PY).read()
    m = re.search(
        r"ROBINHOOD_EQUITIES: dict\[str, tuple\[str, int, str\]\] = (\{.*?\n\})", src, re.S
    )
    if not m:
        raise SystemExit("ROBINHOOD_EQUITIES not found in bot/config/tokens.py")
    return ast.literal_eval(m.group(1))


def load_config() -> dict:
    with open(os.path.join(HERE, "config.json")) as f:
        return json.load(f)


def esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def sector_of(cfg, ticker):
    for sector, tickers in cfg["sectors"].items():
        if ticker in tickers:
            return sector
    return "Other"


def grade_for(cfg, return_bps):
    chosen = cfg["grades"][0]
    for g in cfg["grades"]:
        if return_bps >= g["min_return_bps"]:
            chosen = g
    return chosen


def badge_for(cfg, rank):
    ranks = cfg["economics"]["early_mint_badge_ranks"]
    for name, limit in sorted(ranks.items(), key=lambda kv: kv[1]):
        if rank <= limit:
            return name
    return None


def fmt_px(v):
    if v is None:
        return "—"
    return f"{v:,.2f}" if v >= 1 else f"{v:,.4f}"


# Type stacks. Georgia/Times exist on every consumer platform a marketplace
# renders on; Liberation Serif is the metric-compatible Linux fallback so the
# preview here matches production. No @font-face — a strict-CSP viewer would
# drop it and reflow the whole plate.
SERIF = "Georgia,'Times New Roman','Liberation Serif',serif"
MONO = "'SFMono-Regular',Menlo,Consolas,'DejaVu Sans Mono',monospace"


def _seed(ticker: str, token_id: int, entry) -> int:
    """A stable integer derived from what the token actually IS.

    The engraving is not a random trait roll — it is a function of the ticker
    you chose, the rank you minted at, and the basis stamped on-chain. Two cards
    can only share a plate if they share all three, and nothing here can be
    rerolled after the fact.
    """
    import hashlib

    key = f"{ticker}|{token_id}|{entry if entry else 0}"
    return int.from_bytes(hashlib.sha256(key.encode()).digest()[:8], "big")


def _guilloche(cx, cy, radius, petals, inner, points=240):
    """One arm of an engine-turned rosette (an epitrochoid).

    This is the ornament on scrip, bond coupons and banknotes, and it is here
    for the reason it was there: it is cheap to draw, impossible to redraw by
    hand, and it is generated by the instrument rather than applied to it. One
    path is emitted and then repeated by rotation via <use>, so the whole
    rosette costs a couple of kB instead of the ~300 kB a per-line dump would.
    """
    import math

    d = []
    for i in range(points + 1):
        t = (i / points) * 2 * math.pi
        r = radius * (1 - inner) + radius * inner * math.cos(petals * t)
        x = cx + r * math.cos(t)
        y = cy + r * math.sin(t)
        d.append(f"{'M' if i == 0 else 'L'}{x:.1f} {y:.1f}")
    return "".join(d)


def _small_caps(text, x, y, size, fill, tracking=3.2, weight="normal", family=None, anchor="start"):
    return (
        f'<text x="{x}" y="{y}" font-family="{family or MONO}" font-size="{size}" '
        f'font-weight="{weight}" letter-spacing="{tracking}" fill="{fill}" '
        f'text-anchor="{anchor}">{esc(text.upper())}</text>'
    )


def render_card(
    cfg,
    registry,
    token_id: int,
    ticker: str,
    entry: float | None,
    price: float | None,
    rank: int,
    minted_at: datetime | None = None,
) -> str:
    """Render one position card as an engraved certificate.

    The form is deliberate. This token is a stamped, immutable record of a call
    someone made at a price that can never be edited — which is what scrip has
    always been. So the card is a plate: engine-turned ground, ruled border,
    struck serial, a seal. Every ornament is computed from the token's own
    state, so the engraving is evidence rather than decoration.

    What it still refuses to do is invent history. There is no price chart,
    because there is no price series — only two real numbers, the basis stamped
    at mint and the live oracle. The plate shows exactly those two and the
    distance between them.
    """
    addr, decimals, company = registry[ticker]
    sector = sector_of(cfg, ticker)
    sector_col = cfg["sector_colors"].get(sector, "#94a3b8")
    priced = bool(entry and price and entry > 0)
    ret_bps = int(round((price - entry) / entry * 10_000)) if priced else 0
    grade = grade_for(cfg, ret_bps) if priced else {"name": "Unpriced", "accent": "#8d8577"}
    accent = grade["accent"]
    badge = badge_for(cfg, rank)
    disc = cfg["economics"]["hold_discount_bps"]
    seed = _seed(ticker, token_id, entry)

    # Ornament parameters from real state. Petal count is the token's own
    # fingerprint; the lobe depth OPENS with the size of the move, so a runner
    # visibly blooms and an underwater plate stays tight and closed. The art
    # moves with the position because it is drawn from it.
    petals = 7 + (seed % 12)
    mag = min(abs(ret_bps) / 20_000.0, 1.0) if priced else 0.0
    inner = 0.10 + 0.26 * mag
    spin = (seed >> 8) % 360
    arms = 5 + (seed >> 16) % 4

    W_, H_ = W, H
    PL, PR = 62, W_ - 62  # plate rules
    PT, PB = 62, H_ - 62
    IL, IR = 104, W_ - 104  # inner text column

    p = [
        "<defs>",
        # Ink, not black: a warm plate reads as printed rather than as a screen.
        '<linearGradient id="plate" x1="0" y1="0" x2="0.35" y2="1">'
        '<stop offset="0" stop-color="#12100d"/><stop offset="0.55" stop-color="#0c0b09"/>'
        '<stop offset="1" stop-color="#080706"/></linearGradient>',
        f'<radialGradient id="bloom" cx="0.5" cy="0.5" r="0.5">'
        f'<stop offset="0" stop-color="{accent}" stop-opacity="0.20"/>'
        f'<stop offset="0.65" stop-color="{accent}" stop-opacity="0.05"/>'
        f'<stop offset="1" stop-color="{accent}" stop-opacity="0"/></radialGradient>',
        # Intaglio hatch — the fine parallel ruling of engraved printing.
        '<pattern id="hatch" width="6" height="6" patternUnits="userSpaceOnUse" '
        'patternTransform="rotate(35)">'
        '<line x1="0" y1="0" x2="0" y2="6" stroke="#ffffff" stroke-opacity="0.035" '
        'stroke-width="1"/></pattern>',
        # Fades the ground under the numeral instead of punching a hole in it.
        '<radialGradient id="clear" cx="0.5" cy="0.5" r="0.5">'
        '<stop offset="0" stop-color="#0b0a08" stop-opacity="0.94"/>'
        '<stop offset="0.55" stop-color="#0b0a08" stop-opacity="0.86"/>'
        '<stop offset="1" stop-color="#0b0a08" stop-opacity="0"/></radialGradient>',
        f'<linearGradient id="span" x1="0" y1="0" x2="1" y2="0">'
        f'<stop offset="0" stop-color="{accent}" stop-opacity="0.06"/>'
        f'<stop offset="1" stop-color="{accent}" stop-opacity="0.34"/></linearGradient>',
        # One rosette arm, repeated by rotation below.
        f'<path id="g1" d="{_guilloche(W_ / 2, 620, 236, petals, inner)}"/>',
        f'<path id="g2" d="{_guilloche(W_ / 2, 620, 158, petals + 3, inner * 0.7)}"/>',
        f'<path id="gs" d="{_guilloche(W_ - 214, 1064, 56, petals + 2, inner * 0.8, 160)}"/>',
        # Left-to-right over the top, so the grade reads the right way up.
        f'<path id="sealArc" d="M{W_ - 214 - 60} 1064 A60 60 0 0 1 {W_ - 214 + 60} 1064" '
        f'fill="none"/>',
        "</defs>",
        f'<rect width="{W_}" height="{H_}" fill="url(#plate)"/>',
        f'<rect width="{W_}" height="{H_}" fill="url(#hatch)"/>',
    ]

    # ── engine-turned ground ────────────────────────────────────────────────
    p.append(f'<ellipse cx="{W_ / 2}" cy="620" rx="330" ry="330" fill="url(#bloom)"/>')
    p.append(f'<g stroke="{accent}" fill="none" stroke-width="0.7" opacity="0.5">')
    for i in range(arms * 4):
        a = spin + i * (360.0 / (arms * 4))
        p.append(f'<use href="#g1" transform="rotate({a:.2f} {W_ / 2} 620)" opacity="0.32"/>')
    p.append("</g>")
    p.append(f'<g stroke="{sector_col}" fill="none" stroke-width="0.6" opacity="0.42">')
    for i in range(arms * 3):
        a = -spin + i * (360.0 / (arms * 3))
        p.append(f'<use href="#g2" transform="rotate({a:.2f} {W_ / 2} 620)" opacity="0.30"/>')
    p.append("</g>")

    # ── ruled border, the way scrip is ruled ────────────────────────────────
    p.append(
        f'<rect x="{PL}" y="{PT}" width="{PR - PL}" height="{PB - PT}" fill="none" '
        f'stroke="{accent}" stroke-opacity="0.55" stroke-width="2.5"/>'
        f'<rect x="{PL + 9}" y="{PT + 9}" width="{PR - PL - 18}" height="{PB - PT - 18}" '
        f'fill="none" stroke="{accent}" stroke-opacity="0.28" stroke-width="0.8"/>'
    )
    for cx_, cy_ in ((PL + 9, PT + 9), (PR - 9, PT + 9), (PL + 9, PB - 9), (PR - 9, PB - 9)):
        p.append(
            f'<circle cx="{cx_}" cy="{cy_}" r="15" fill="none" stroke="{accent}" '
            f'stroke-opacity="0.45" stroke-width="0.9"/>'
            f'<circle cx="{cx_}" cy="{cy_}" r="6.5" fill="none" stroke="{accent}" '
            f'stroke-opacity="0.7" stroke-width="0.9"/>'
        )

    # ── head ────────────────────────────────────────────────────────────────
    y = 126
    p.append(_small_caps("Suwappu", IL, y, 17, "#e9e2d4", 7.5, "bold"))
    p.append(
        _small_caps("Certificate of Position", W_ / 2, y, 12, "#8a8474", 4.2, anchor="middle")
    )
    serial = f"No. {rank:04d}"
    p.append(
        f'<text x="{IR}" y="{y}" font-family="{SERIF}" font-size="19" fill="{accent}" '
        f'fill-opacity="0.92" text-anchor="end" letter-spacing="1.5">{esc(serial)}</text>'
    )
    p.append(
        f'<line x1="{IL}" y1="{y + 20}" x2="{IR}" y2="{y + 20}" stroke="{accent}" '
        f'stroke-opacity="0.35" stroke-width="1"/>'
    )

    # ── ticker + issuer ─────────────────────────────────────────────────────
    p.append(
        f'<text x="{IL}" y="284" font-family="{SERIF}" font-size="132" font-weight="bold" '
        f'fill="#f3ece0" letter-spacing="-2">{esc(ticker)}</text>'
    )
    if len(company) <= 42:
        name = company
    else:
        cut = company[:42].rsplit(" ", 1)[0]
        name = (cut if len(cut) > 20 else company[:41]) + "\u2026"
    p.append(_small_caps(name, IL, 320, 15, "#9d9585", 3.4))
    p.append(_small_caps(f"{sector} \u00b7 Robinhood Chain", IL, 348, 11.5, sector_col, 3.0))
    if badge:
        p.append(
            f'<text x="{IR}" y="284" font-family="{SERIF}" font-size="26" fill="{accent}" '
            f'fill-opacity="0.8" text-anchor="end" font-style="italic">{esc(badge)}</text>'
        )

    # ── the two real numbers, and the distance between them ─────────────────
    if priced:
        sign = "+" if ret_bps >= 0 else "\u2212"
        hero = f"{sign}{abs(ret_bps) / 100:,.1f}%"
        # Knock a clear disc out of the rosette so the number reads. A guilloché
        # is a ground, not a backdrop for type — laid directly under a 140px
        # numeral it turned both to mud.
        p.append(f'<ellipse cx="{W_ / 2}" cy="620" rx="300" ry="212" fill="url(#clear)"/>')
        p.append(_small_caps("return since entry", W_ / 2, 566, 11.5, "#8a8474", 5.5, anchor="middle"))
        # Fit to the string: "+257.2%" is two glyphs wider than "-5.7%" and at a
        # fixed size ran straight through the rosette's outer ring.
        hsize = 122 if len(hero) <= 6 else (108 if len(hero) <= 7 else 94)
        p.append(
            f'<text x="{W_ / 2}" y="666" font-family="{SERIF}" font-size="{hsize}" '
            f'font-weight="bold" fill="{accent}" text-anchor="middle" '
            f'letter-spacing="-3">{esc(hero)}</text>'
        )
        p.append(
            f'<line x1="{W_ / 2 - 92}" y1="700" x2="{W_ / 2 + 92}" y2="700" stroke="{accent}" '
            f'stroke-opacity="0.4" stroke-width="1"/>'
        )
        p.append(
            _small_caps(
                f"{'gain' if ret_bps >= 0 else 'drawdown'} on basis",
                W_ / 2,
                726,
                10.5,
                "#7b756a",
                4.0,
                anchor="middle",
            )
        )

        # An engraved scale, not a fabricated chart. Two marks: where the basis
        # was struck, where the oracle is now. Nothing between them is known, so
        # nothing between them is drawn except the span itself.
        sy = 820
        p.append(
            f'<line x1="{IL}" y1="{sy}" x2="{IR}" y2="{sy}" stroke="#4a4740" stroke-width="1"/>'
        )
        for k in range(1, 24):
            tx = IL + (IR - IL) * k / 24.0
            tall = 9 if k % 6 == 0 else 5
            p.append(
                f'<line x1="{tx:.1f}" y1="{sy - tall}" x2="{tx:.1f}" y2="{sy + tall}" '
                f'stroke="#4a4740" stroke-width="0.8"/>'
            )
        span = IR - IL
        e_x = IL + (0 if price >= entry else span)
        n_x = IL + (span if price >= entry else 0)
        # Gradient runs entry -> now, so it always brightens toward the live
        # price rather than flipping direction on a losing position.
        flip = " transform=\"rotate(180 500 0)\"" if n_x < e_x else ""
        p.append(
            f'<rect x="{min(e_x, n_x)}" y="{sy - 15}" width="{abs(n_x - e_x)}" height="30" '
            f'fill="url(#span)"{flip}/>'
        )
        for xx, lab, val, col in (
            (e_x, "entry", fmt_px(entry), "#9d9585"),
            (n_x, "now", fmt_px(price), accent),
        ):
            anc = "start" if xx < W_ / 2 else "end"
            p.append(
                f'<line x1="{xx}" y1="{sy - 22}" x2="{xx}" y2="{sy + 22}" stroke="{col}" '
                f'stroke-width="2"/>'
            )
            p.append(_small_caps(lab, xx, sy - 34, 11, "#8a8474", 4.0, anchor=anc))
            p.append(
                f'<text x="{xx}" y="{sy + 48}" font-family="{SERIF}" font-size="30" '
                f'fill="{col}" text-anchor="{anc}">${esc(val)}</text>'
            )
    else:
        p.append(
            f'<ellipse cx="{W_ / 2}" cy="620" rx="300" ry="212" fill="url(#clear)"/>'
        )
        p.append(
            f'<text x="{W_ / 2}" y="650" font-family="{SERIF}" font-size="76" '
            f'fill="#8d8577" text-anchor="middle" font-style="italic" '
            f'letter-spacing="2">Unpriced</text>'
        )
        p.append(
            _small_caps(
                "no oracle price at mint \u00b7 no basis stamped",
                W_ / 2,
                700,
                12,
                "#6f6a5e",
                4.0,
                anchor="middle",
            )
        )
        p.append(
            f'<line x1="{IL + 150}" y1="820" x2="{IR - 150}" y2="820" stroke="#3b3830" '
            f'stroke-width="1" stroke-dasharray="3 7"/>'
        )

    # ── the record ──────────────────────────────────────────────────────────
    ry = 950
    p.append(
        f'<line x1="{IL}" y1="{ry - 34}" x2="{IR}" y2="{ry - 34}" stroke="{accent}" '
        f'stroke-opacity="0.22" stroke-width="0.8"/>'
    )
    held = minted_at.strftime("%d %b %Y").upper() if minted_at else "\u2014"
    facts = [
        ("Struck", held),
        ("Rank", f"{rank} of {cfg['collection']['supply']:,}"),
        ("Basis", f"${fmt_px(entry)}" if priced else "\u2014"),
    ]
    for i, (lab, val) in enumerate(facts):
        fx = IL + i * 196  # left-packed: the seal owns the right of the plate
        p.append(_small_caps(lab, fx, ry, 10.5, "#7b756a", 3.6))
        p.append(
            f'<text x="{fx}" y="{ry + 30}" font-family="{SERIF}" font-size="24" '
            f'fill="#ddd5c6">{esc(val)}</text>'
        )

    # ── seal: the grade, struck rather than labelled ────────────────────────
    # Pulled inside the plate rule (r=86 at x=W-196 crossed it) and moved clear
    # of the Basis column it was sitting on top of.
    scx, scy, sr = W_ - 214, 1064, 74
    p.append(
        f'<circle cx="{scx}" cy="{scy}" r="{sr}" fill="#0b0a08" fill-opacity="0.75"/>'
        f'<circle cx="{scx}" cy="{scy}" r="{sr}" fill="none" stroke="{accent}" '
        f'stroke-opacity="0.55" stroke-width="2"/>'
        f'<circle cx="{scx}" cy="{scy}" r="{sr - 9}" fill="none" stroke="{accent}" '
        f'stroke-opacity="0.28" stroke-width="0.8"/>'
    )
    # A small rosette struck into the seal, same instrument as the ground.
    p.append(f'<g stroke="{accent}" fill="none" stroke-width="0.5" opacity="0.30">')
    for i in range(6):
        p.append(
            f'<use href="#gs" transform="rotate({spin + i * 60:.1f} {scx} {scy})"/>'
        )
    p.append("</g>")
    # Grade around the top of the seal — the reason a seal is round.
    p.append(
        f'<text font-family="{MONO}" font-size="11" fill="{accent}" fill-opacity="0.85" '
        f'letter-spacing="3.6"><textPath href="#sealArc" startOffset="50%" '
        f'text-anchor="middle">{esc(grade["name"].upper())}</textPath></text>'
    )
    p.append(
        f'<text x="{scx}" y="{scy + 10}" font-family="{SERIF}" font-size="30" '
        f'font-weight="bold" fill="#ede5d7" text-anchor="middle">{esc(ticker[:4])}</text>'
    )
    p.append(_small_caps(f"no {rank}", scx, scy + 40, 9, "#7b756a", 2.6, anchor="middle"))

    # ── holder's right, stated plainly ──────────────────────────────────────
    p.append(
        f'<text x="{IL}" y="{scy - 24}" font-family="{SERIF}" font-size="27" fill="#ddd5c6">'
        f'\u2212{disc} bps on every Suwappu swap</text>'
    )
    p.append(_small_caps(f"${disc / 10:.2f} back per $1,000 traded", IL, scy + 8, 12, "#8a8474", 3.2))
    p.append(
        f'<text x="{IL}" y="{scy + 42}" font-family="{MONO}" font-size="10" fill="#5f5a51" '
        f'letter-spacing="0.4">{esc(addr)}</text>'
    )

    # ── plate footer ────────────────────────────────────────────────────────
    p.append(
        _small_caps(
            "Collectible \u00b7 not equity \u00b7 not a security \u00b7 pays nothing \u00b7 "
            "no claim on any issuer",
            IL,
            PB - 30,
            9.5,
            "#57534a",
            2.2,
        )
    )
    p.append(_small_caps(f"chain 4663 \u00b7 token {token_id}", IR, PB - 30, 9.5, "#57534a", 2.2, anchor="end"))

    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W_}" height="{H_}" '
        f'viewBox="0 0 {W_} {H_}" role="img" aria-label="{esc(ticker)} position card">'
        + "".join(p)
        + "</svg>"
    )


def build_metadata(cfg, registry, token_id, ticker, entry, price, rank, minted_at=None):
    """ERC-721 metadata for a live position. Regenerated on every fetch — the
    return and grade move with the market, so this is deliberately dynamic."""
    addr, decimals, company = registry[ticker]
    priced = bool(entry and price and entry > 0)
    ret_bps = int(round((price - entry) / entry * 10_000)) if priced else 0
    grade = grade_for(cfg, ret_bps) if priced else {"name": "Unpriced"}
    col = cfg["collection"]
    badge = badge_for(cfg, rank)

    attrs = [
        {"trait_type": "Ticker", "value": ticker},
        {"trait_type": "Company", "value": company},
        {"trait_type": "Sector", "value": sector_of(cfg, ticker)},
        {"trait_type": "Grade", "value": grade["name"]},
        {"trait_type": "Mint Rank", "value": rank, "display_type": "number"},
    ]
    if badge:
        attrs.append({"trait_type": "Badge", "value": badge})
    if priced:
        attrs += [
            {"trait_type": "Entry Price", "value": round(entry, 4)},
            {
                "trait_type": "Return %",
                "value": round(ret_bps / 100.0, 2),
                "display_type": "number",
            },
        ]
    if minted_at:
        attrs.append(
            {
                "trait_type": "Held Since",
                "value": int(minted_at.timestamp()),
                "display_type": "date",
            }
        )

    if priced:
        desc = (
            f"A position on {company} ({ticker}) opened on Robinhood Chain at "
            f"${fmt_px(entry)}. Currently ${fmt_px(price)} — "
            f"{'up' if ret_bps >= 0 else 'down'} {abs(ret_bps) / 100:.1f}%. "
            f"Mint rank {rank} of 10,000.\n\n"
            f"The entry price was stamped on-chain at mint and can never change; the "
            f"card re-renders against the live price, so what you see is the call you "
            f"actually made. Holding it takes "
            f"{cfg['economics']['hold_discount_bps']} bps off every Suwappu swap.\n\n"
            f"{col['compliance']}"
        )
    else:
        desc = (
            f"A position on {company} ({ticker}) on Robinhood Chain, minted while no "
            f"oracle price was available, so no entry basis was stamped and no return "
            f"is tracked. Mint rank {rank} of 10,000.\n\n{col['compliance']}"
        )

    return {
        "name": (f"{ticker} #{rank}" + (f" · {grade['name']}" if priced else " · Unpriced")),
        "description": desc,
        "image": f"{col['external_url']}/card/{token_id}.svg",
        "external_url": f"{col['external_url']}/{token_id}",
        "attributes": attrs,
        "properties": {
            "chain_id": col["chain"]["chain_id"],
            "underlying_erc20": addr,
            "underlying_decimals": decimals,
            "disclaimer": col["compliance"],
        },
    }


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--gallery", action="store_true")
    ap.add_argument("--ticker", default="NVDA")
    ap.add_argument("--entry", type=float, default=100.0)
    ap.add_argument("--price", type=float, default=137.0)
    ap.add_argument("--rank", type=int, default=42)
    ap.add_argument("--out", default=os.path.join(HERE, "preview"))
    args = ap.parse_args()

    cfg, registry = load_config(), load_registry()
    os.makedirs(args.out, exist_ok=True)

    if args.gallery:
        # Current prices are the REAL values read from the Chainlink feeds on
        # chain 4663 (see feeds.json / verify_feeds.py). Entries are illustrative
        # basis points in time, since nothing has been minted yet.
        feeds = json.load(open(os.path.join(HERE, "feeds.json")))["feeds"]
        samples = [
            ("NVDA", 0.42, 1),
            ("SPCX", 0.28, 318),
            ("AAPL", 1.06, 1804),
            ("IONQ", 1.19, 5522),
            ("GME", 1.55, 9310),
            ("TSLA", None, 7781),
        ]
        for i, (tk, ratio, rank) in enumerate(samples, start=1):
            price = feeds[tk]["verified_price_usd"]
            entry = round(price * ratio, 2) if ratio else None
            minted = datetime(2026, 8, 1 + (i % 12), 9, 0, tzinfo=timezone.utc)
            svg = render_card(
                cfg, registry, i, tk, entry, price if ratio else None, rank, minted
            )
            open(os.path.join(args.out, f"{tk}.svg"), "w").write(svg)
        print(f"gallery -> {args.out} (current prices are live feed values)")
    else:
        svg = render_card(cfg, registry, 1, args.ticker, args.entry, args.price, args.rank)
        path = os.path.join(args.out, f"{args.ticker}.svg")
        open(path, "w").write(svg)
        print(path)
