#!/usr/bin/env python3
"""Suwappu Positions — live position-card renderer.

A card is drawn from REAL state only: the ticker you chose, the entry price
stamped on-chain when you minted, and the current oracle price. Nothing here
invents price history — the previous iteration of this collection drew a fake
random-walk chart, which is exactly the kind of decoration that makes a card
worthless. The hero element is the actual return between two real numbers.

The ticker universe (symbol, ERC-20 address, decimals, company name) is parsed
from bot/config/tokens.py::ROBINHOOD_EQUITIES so the collection cannot drift
from what is tradable on chain 4663.

  python3 nft/position-cards/render.py --gallery        # sample cards -> preview/
  python3 nft/position-cards/render.py --ticker NVDA --entry 100 --price 168 --rank 42
"""

import argparse
import ast
import json
import os
import re
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
TOKENS_PY = os.path.join(REPO, "bot", "config", "tokens.py")

W, H = 1000, 1250
M = 44
CX0, CX1 = M, W - M
PAD = 38
IX0, IX1 = CX0 + PAD, CX1 - PAD


def load_registry() -> dict:
    src = open(TOKENS_PY).read()
    m = re.search(
        r"ROBINHOOD_EQUITIES: dict\[str, tuple\[str, int, str\]\] = (\{.*?\n\})", src, re.S
    )
    if not m:
        raise SystemExit("ROBINHOOD_EQUITIES not found in bot/config/tokens.py")
    return ast.literal_eval(m.group(1))


def load_config() -> dict:
    with open(os.path.join(HERE, "config.json")) as f:
        return json.load(f)


def esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def sector_of(cfg, ticker):
    for sector, tickers in cfg["sectors"].items():
        if ticker in tickers:
            return sector
    return "Other"


def grade_for(cfg, return_bps):
    chosen = cfg["grades"][0]
    for g in cfg["grades"]:
        if return_bps >= g["min_return_bps"]:
            chosen = g
    return chosen


def badge_for(cfg, rank):
    ranks = cfg["economics"]["early_mint_badge_ranks"]
    for name, limit in sorted(ranks.items(), key=lambda kv: kv[1]):
        if rank <= limit:
            return name
    return None


def fmt_px(v):
    if v is None:
        return "—"
    return f"{v:,.2f}" if v >= 1 else f"{v:,.4f}"


# Type stacks. Georgia/Times exist on every consumer platform a marketplace
# renders on; Liberation Serif is the metric-compatible Linux fallback so the
# preview here matches production. No @font-face — a strict-CSP viewer would
# drop it and reflow the whole plate.
# The site loads Geist and falls back to system-ui; a card cannot @font-face
# under a marketplace CSP, so this names Geist first and lands on the same
# grotesque skeleton everywhere else. Liberation Sans is the Linux fallback, so
# the preview rendered here matches what a browser shows.
DISPLAY = "Geist,'Inter',system-ui,-apple-system,'Liberation Sans',Arial,sans-serif"
MONO = "'Geist Mono','SFMono-Regular',Menlo,Consolas,'DejaVu Sans Mono',monospace"
# Retained name so the seal and any older reference still resolve.
SERIF = DISPLAY


def _seed(ticker: str, token_id: int, entry) -> int:
    """A stable integer derived from what the token actually IS.

    The engraving is not a random trait roll — it is a function of the ticker
    you chose, the rank you minted at, and the basis stamped on-chain. Two cards
    can only share a plate if they share all three, and nothing here can be
    rerolled after the fact.
    """
    import hashlib

    key = f"{ticker}|{token_id}|{entry if entry else 0}"
    return int.from_bytes(hashlib.sha256(key.encode()).digest()[:8], "big")


def _guilloche(cx, cy, radius, petals, inner, points=240):
    """One arm of an engine-turned rosette (an epitrochoid).

    This is the ornament on scrip, bond coupons and banknotes, and it is here
    for the reason it was there: it is cheap to draw, impossible to redraw by
    hand, and it is generated by the instrument rather than applied to it. One
    path is emitted and then repeated by rotation via <use>, so the whole
    rosette costs a couple of kB instead of the ~300 kB a per-line dump would.
    """
    import math

    d = []
    for i in range(points + 1):
        t = (i / points) * 2 * math.pi
        r = radius * (1 - inner) + radius * inner * math.cos(petals * t)
        x = cx + r * math.cos(t)
        y = cy + r * math.sin(t)
        d.append(f"{'M' if i == 0 else 'L'}{x:.1f} {y:.1f}")
    return "".join(d)


def _small_caps(text, x, y, size, fill, tracking=3.2, weight="normal", family=None, anchor="start"):
    return (
        f'<text x="{x}" y="{y}" font-family="{family or MONO}" font-size="{size}" '
        f'font-weight="{weight}" letter-spacing="{tracking}" fill="{fill}" '
        f'text-anchor="{anchor}">{esc(text.upper())}</text>'
    )


# ─── engraving families ──────────────────────────────────────────────────────
# Six authentic engine-turning patterns, not six settings of one. A rose engine
# and a straight-line engine cut fundamentally different geometry, and these
# mirror that split: rosette / waves / moire / sunburst come off the rose engine,
# barleycorn and clous de Paris off the straight-line. Which one a plate gets is
# a STRUCTURAL choice, so two cards are not the same composition recoloured.
#
# Sizing note that applies to all six: stroke weights are set for a ~190px
# marketplace thumbnail, which is a 5x reduction. Hairlines are invisible there.

ENGRAVINGS = ("rosette", "waves", "barleycorn", "hobnail", "sunburst", "moire")
COMPOSITIONS = ("medallion", "field", "band", "twin")
INKS = ("line", "double", "stipple")


def _eng_rosette(cx, cy, r, seed, petals, inner):
    """Rose-engine rosette: an epitrochoid, repeated by rotation."""
    arms = 5 + (seed >> 16) % 4
    defs = f'<path id="e1" d="{_guilloche(cx, cy, r, petals, inner)}"/>'
    body = "".join(
        f'<use href="#e1" transform="rotate({(seed % 360) + i * (360.0 / (arms * 3)):.2f} '
        f'{cx} {cy})" opacity="0.34"/>'
        for i in range(arms * 3)
    )
    return defs, body


def _eng_moire(cx, cy, r, seed, petals, inner):
    """Two ring stacks struck from offset centres — the interference IS the
    pattern, which is why moire was used on scrip that had to resist copying."""
    off = 14 + (seed % 22)
    rings = 16 + (seed >> 4) % 10
    out = []
    for i in range(rings):
        rr = r * (0.24 + 0.76 * (i + 1) / rings)
        out.append(f'<circle cx="{cx - off}" cy="{cy}" r="{rr:.1f}"/>')
        out.append(f'<circle cx="{cx + off}" cy="{cy}" r="{rr:.1f}"/>')
    return "", "".join(out)


def _eng_sunburst(cx, cy, r, seed, petals, inner):
    """Straight radial rays of modulated length — a rayon flamme burst."""
    import math

    n = 72 + (seed % 5) * 24
    out = []
    for i in range(n):
        a = 2 * math.pi * i / n
        rr = r * (0.62 + 0.38 * abs(math.cos(petals * a / 2)))
        out.append(
            f'<line x1="{cx + math.cos(a) * r * 0.2:.1f}" y1="{cy + math.sin(a) * r * 0.2:.1f}" '
            f'x2="{cx + math.cos(a) * rr:.1f}" y2="{cy + math.sin(a) * rr:.1f}"/>'
        )
    return "", "".join(out)


def _eng_waves(cx, cy, r, seed, petals, inner):
    """Rose-engine waves: parallel bands whose phase walks, so the field reads
    as a woven ripple rather than as stripes."""
    import math

    rows = 26
    amp = 10 + (seed % 16)
    freq = 0.010 + ((seed >> 3) % 9) * 0.0016
    out = []
    for row in range(rows):
        y0 = cy - r + (2 * r) * row / (rows - 1)
        ph = row * 0.55
        pts = [
            f"{cx - r * 1.35 + (2.7 * r) * i / 40:.0f} "
            f"{y0 + amp * math.sin(freq * (2.7 * r) * i / 40 * 6.28 + ph):.1f}"
            for i in range(41)
        ]
        out.append(f'<path d="M{"L".join(pts)}"/>')
    return "", "".join(out)


def _eng_barleycorn(cx, cy, r, seed, petals, inner):
    """Grain d'orge: interlaced diagonal lattice off the straight-line engine.
    Tiled as a <pattern>, so a full-bleed field costs a few hundred bytes."""
    step = 22 + (seed % 12)
    defs = (
        f'<pattern id="ebar" width="{step}" height="{step}" patternUnits="userSpaceOnUse" '
        f'patternTransform="rotate({30 + seed % 30})">'
        f'<path d="M0 0 L{step} {step} M{step} 0 L0 {step}" fill="none" '
        f'stroke="currentColor" stroke-width="1.6"/>'
        f'<circle cx="{step / 2}" cy="{step / 2}" r="{step / 5:.1f}" fill="none" '
        f'stroke="currentColor" stroke-width="1.2"/></pattern>'
    )
    return defs, "__PATTERN__ebar"


def _eng_hobnail(cx, cy, r, seed, petals, inner):
    """Clous de Paris: the pyramid grid. Straight-line engine, tiled."""
    step = 18 + (seed % 14)
    h = step / 2
    defs = (
        f'<pattern id="ehob" width="{step}" height="{step}" patternUnits="userSpaceOnUse" '
        f'patternTransform="rotate({seed % 45})">'
        f'<path d="M{h} 0 L{step} {h} L{h} {step} L0 {h} Z" fill="none" '
        f'stroke="currentColor" stroke-width="1.5"/>'
        f'<path d="M{h} {h * 0.45} L{step * 0.78} {h} L{h} {step - h * 0.45} L{step * 0.22} {h} Z" '
        f'fill="none" stroke="currentColor" stroke-width="1"/></pattern>'
    )
    return defs, "__PATTERN__ehob"


_ENGRAVERS = {
    "rosette": _eng_rosette,
    "moire": _eng_moire,
    "sunburst": _eng_sunburst,
    "waves": _eng_waves,
    "barleycorn": _eng_barleycorn,
    "hobnail": _eng_hobnail,
}


def _mix(a: str, b: str, t: float) -> str:
    """Blend two #rrggbb colours. Used to build a per-card field colour so the
    collection reads as families in a grid rather than 10,000 black rectangles."""
    ca = tuple(int(a[i : i + 2], 16) for i in (1, 3, 5))
    cb = tuple(int(b[i : i + 2], 16) for i in (1, 3, 5))
    return "#" + "".join(f"{round(x + (y - x) * t):02x}" for x, y in zip(ca, cb))


def _lum(hexcol: str) -> float:
    """Relative luminance, WCAG-style."""

    def ch(v):
        v = v / 255.0
        return v / 12.92 if v <= 0.04045 else ((v + 0.055) / 1.055) ** 2.4

    r, g, b = (int(hexcol[i : i + 2], 16) for i in (1, 3, 5))
    return 0.2126 * ch(r) + 0.7152 * ch(g) + 0.0722 * ch(b)


def contrast(a: str, b: str) -> float:
    """WCAG contrast ratio between two #rrggbb colours (1.0 to 21.0)."""
    la, lb = _lum(a), _lum(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


# ── the luxury metal system ──────────────────────────────────────────────────
# The plate is a card in the Centurion / Robinhood Gold lineage: a matte
# near-black ground, tone-on-tone engraving, and a small amount of struck
# metal. Which metal is a TIER, not a mood — Founder cards are furnished in
# gold, Early in platinum, the base plate in graphite — so status reads from
# across the room the way a heavy card reads across a table.
CHARCOAL = "#0d0d10"  # the matte ground; sector tint is anodised into it
IVORY = "#f2ede3"  # ink on the dark plate / ground of the rare Gilt proof
# Three clearly STEPPED luminances, brightest at the top tier — the first cut
# had gold measurably dimmer than platinum, so the top tier read as second.
GOLD = "#e0bd76"
PLATINUM = "#aab1b9"
GRAPHITE = "#8b8e94"


def metal_for(badge: str | None, sector_col: str) -> str:
    """The furniture metal for a plate. Earned by mint rank, never rolled."""
    if badge == "Founder":
        return GOLD
    if badge == "Early":
        return PLATINUM
    return _mix("#6e7176", sector_col, 0.18)


def palette(cfg, sector_col, accent, ret_bps, priced, proof):
    """Every colour a plate uses, in one place.

    Extracted because render_card and card_traits were each computing this
    independently, so the quality gate measured a palette the renderer had
    stopped using — the same two-implementations-of-one-rule bug that keeps
    turning up in this repo. One function, both callers.
    """
    b = cfg["brand"]
    if proof:  # Gilt proof — the rare plate that leaves the dark: ivory, dark ink
        field = _mix(b["bg"], sector_col, 0.07)
        hero = _mix(accent, b["text"], 0.55)
        if priced and ret_bps >= 2500:
            hero = _mix(b["green"], accent, 0.25)
        elif priced and ret_bps < -200:
            hero = "#8f3a44"
        return {
            "field": field,
            "field2": _mix(field, "#eae3d5", 0.55),
            "edge": _mix(field, "#d8d0c0", 0.60),
            "rim": _mix("#9c8b62", sector_col, 0.25),
            "body": b["text"],
            "quiet": b["text-2"],
            "hero": hero,
            "mark": b["accent"],
        }
    # The default plate. Sector colour is anodised into the ground — ten
    # families sort by eye in a grid, but each reads as a tinted metal,
    # not a pastel. Gains keep the accent ramp (jade climbing to champagne),
    # lifted toward ivory so the numeral clears the contrast floor; losses take
    # a muted oxblood — expensive, not alarming.
    hero = _mix(accent, IVORY, 0.45)
    if priced and ret_bps >= 2500:
        hero = _mix(accent, IVORY, 0.32)
    elif priced and ret_bps < -200:
        hero = "#c4767c"
    # Anodising is luminance-normalised, not a flat mix. A constant 15% let the
    # warm high-luminance families (Crypto gold, Media rose) lift visibly off
    # black while the cool ones stayed flat — a 28% spread in field luminance.
    # Scaling by the sector's own luminance keeps all ten fields at roughly the
    # same darkness while the HUE still sorts the wall. (At the original flat
    # 6% every field converged on the same black and families didn't sort.)
    t = min(0.18, max(0.10, 0.15 * (0.34 / max(_lum(sector_col), 0.05)) ** 0.5))
    field = _mix(CHARCOAL, sector_col, t)
    rim = _mix(sector_col, GRAPHITE, 0.55)
    if priced and ret_bps >= 200:
        # A winner's engraving takes the grade's metal. Warm sector ornament
        # (Media rose) otherwise read as a loss from across the wall, however
        # green the numeral — the ornament is the biggest colour field there is.
        rim = _mix(rim, accent, 0.35)
    return {
        "field": field,
        "field2": _mix(field, "#000000", 0.35),
        "edge": _mix(field, sector_col, 0.22),
        "rim": rim,
        "body": b["bg"],
        "quiet": _mix(GRAPHITE, IVORY, 0.30),
        "hero": hero,
        "mark": b["accent"],
    }


def card_traits(cfg, registry, token_id, ticker, entry, price, rank):
    """The structural choices a plate resolves to, plus its legibility numbers.

    Long-form generative work cannot rely on the artist culling weak outputs —
    a collector sees the entire space. So the sweep enforces a floor on every
    one of the 10,000 rather than trusting a spot check of a contact sheet.
    """
    priced = bool(entry and price and entry > 0)
    ret_bps = int(round((price - entry) / entry * 10_000)) if priced else 0
    grade = grade_for(cfg, ret_bps) if priced else {"name": "Unpriced", "accent": "#8d8577"}
    accent = grade["accent"]
    sector = sector_of(cfg, ticker)
    sector_col = cfg["sector_colors"].get(sector, "#94a3b8")
    seed = _seed(ticker, token_id, entry)
    mag = min(abs(ret_bps) / 20_000.0, 1.0) if priced else 0.0
    lift = max(-1.0, min(1.0, (ret_bps / 20_000.0) if priced else 0.0))

    allowed = ["medallion", "band"] if lift < 0.05 else list(COMPOSITIONS)
    if mag < 0.02:
        allowed = ["medallion"]
    proof = (seed >> 44) % 40 == 0
    pal = palette(cfg, sector_col, accent, ret_bps, priced, proof)
    return {
        "engraving": ENGRAVINGS[(seed >> 24) % len(ENGRAVINGS)],
        "ink": INKS[(seed >> 32) % len(INKS)],
        "composition": allowed[(seed >> 36) % len(allowed)],
        "proof": proof,
        "sector": sector,
        "grade": grade["name"],
        "hero_contrast": round(contrast(pal["hero"], pal["field"]), 2),
        "body_contrast": round(contrast(pal["body"], pal["field"]), 2),
    }


def render_card(
    cfg,
    registry,
    token_id: int,
    ticker: str,
    entry: float | None,
    price: float | None,
    rank: int,
    minted_at: datetime | None = None,
) -> str:
    """Render one position card as an engraved plate.

    The form is deliberate. This token is a stamped, immutable record of a call
    someone made at a price that can never be edited — which is what scrip has
    always been. So the card is a plate: engine-turned ground, ruled border,
    struck serial, a seal.

    Every decision below is answerable to the GRID. Almost nobody meets an NFT
    at full size; they meet 40 of them at 190px in a marketplace wall, and a
    plate that only works as a hero shot does not get minted. So:

      * the field carries a sector colour, so the collection reads as ten
        families instead of 10,000 near-black rectangles;
      * the engraving is stroked heavily enough to survive a 5x downscale
        (hairlines at 1000px are simply gone at 190px);
      * the rosette's scale and height move with the return, so a wall of cards
        has visible rhythm rather than one repeated composition;
      * the plate is mostly image — four stacked bands of micro-type read as
        grey mush at thumbnail size, so there is now one.

    What it still refuses to do is invent history. There is no price series,
    only the basis stamped at mint and the live oracle, and the plate shows
    exactly those two.
    """
    addr, decimals, company = registry[ticker]
    sector = sector_of(cfg, ticker)
    sector_col = cfg["sector_colors"].get(sector, "#94a3b8")
    priced = bool(entry and price and entry > 0)
    ret_bps = int(round((price - entry) / entry * 10_000)) if priced else 0
    grade = grade_for(cfg, ret_bps) if priced else {"name": "Unpriced", "accent": "#8d8577"}
    accent = grade["accent"]
    badge = badge_for(cfg, rank)
    disc_pct = int(round(cfg["economics"]["hold_discount_fraction"] * 100))
    seed = _seed(ticker, token_id, entry)

    # ── STRUCTURAL modes, not parameter jitter ──────────────────────────────
    # Long-form generative work has nowhere to hide: a collector sees the whole
    # output space, so an algorithm that emits one composition 10,000 times
    # reads as an edition that was too large. Variety here is combinatorial and
    # structural — 6 engraving families x 4 compositions x 3 inks x 10 sector
    # palettes, plus a rare proof state — rather than one plate recoloured.
    #
    # None of it is a trait roll. The choice is drawn from a hash of what the
    # token actually IS (ticker, mint rank, stamped basis), and the position
    # BIASES the draw: only a real runner can be struck full-bleed, and only a
    # deep drawdown gets the closed, tight plates. The engraving is evidence.
    mag = min(abs(ret_bps) / 20_000.0, 1.0) if priced else 0.0
    lift = max(-1.0, min(1.0, (ret_bps / 20_000.0) if priced else 0.0))

    engraving = ENGRAVINGS[(seed >> 24) % len(ENGRAVINGS)]
    ink = INKS[(seed >> 32) % len(INKS)]
    # Composition is earned. Full-bleed is reserved for positions that actually
    # ran; a losing plate cannot buy the loudest layout.
    allowed = ["medallion", "band"] if lift < 0.05 else list(COMPOSITIONS)
    if mag < 0.02:
        allowed = ["medallion"]  # a flat position gets the quietest plate
    composition = allowed[(seed >> 36) % len(allowed)]
    # Proof state: a light plate struck in dark ink. Rare (about 1 in 40) and a
    # complete inversion rather than another palette, so it is legible as rare
    # from across a wall instead of needing a trait table to notice.
    proof = (seed >> 44) % 40 == 0

    rad = 200 + int(mag * 82)
    cy = max(672 - int(lift * 52), 372 + rad)
    petals = 7 + (seed % 12)
    inner = 0.12 + 0.26 * mag
    spin = (seed >> 8) % 360

    # ── luxury, not loud ────────────────────────────────────────────────────
    # The default plate is a matte near-black card in the Amex Centurion /
    # Robinhood Gold lineage: charcoal ground with the sector anodised in,
    # tone-on-tone engraving, ivory ink, and the only saturated thing on the
    # plate is the small pink Suwappu mark. Status is carried by struck METAL —
    # gold for Founder, platinum for Early, graphite for the base plate. The
    # rare inversion is the "Gilt proof": an ivory plate in dark ink, the way a
    # black-tie house prints its daytime stationery.
    b = cfg["brand"]
    pal = palette(cfg, sector_col, accent, ret_bps, priced, proof)
    field, field2, edge_col = pal["field"], pal["field2"], pal["edge"]
    rim, body_col, quiet, hero_col, mark_col = (
        pal["rim"],
        pal["body"],
        pal["quiet"],
        pal["hero"],
        pal["mark"],
    )
    # Furniture metal. On the ivory Gilt proof the raw metals are too close to
    # the ground, so they are struck darker there.
    metal = metal_for(badge, sector_col)
    if proof:
        metal = _mix(metal, b["text"], 0.40)
    faint = _mix(quiet, field, 0.35)  # small print: legible, deliberately quiet

    W_, H_ = W, H
    PL, PR, PT, PB = 54, W_ - 54, 54, H_ - 54
    IL, IR = 96, W_ - 96

    # Composition decides WHERE the engraving is cut; the family decides WHAT
    # is cut. Keeping the two independent is what turns 6 + 4 into 24 distinct
    # plates instead of six layouts with an ornament bolted on.
    if composition == "field":
        eng_cx, eng_cy, eng_r = W_ / 2, H_ / 2, 660
        clip_shape = (
            f'<rect x="{PL + 12}" y="{PT + 12}" width="{PR - PL - 24}" '
            f'height="{PB - PT - 24}"/>'
        )
    elif composition == "band":
        eng_cx, eng_cy, eng_r = W_ / 2, cy, rad * 1.55
        clip_shape = f'<rect x="{PL + 12}" y="{cy - 236}" width="{PR - PL - 24}" height="472"/>'
    elif composition == "twin":
        eng_cx, eng_cy, eng_r = W_ / 2, cy, rad * 0.92
        clip_shape = (
            f'<circle cx="{W_ / 2 - rad * 0.5:.0f}" cy="{cy}" r="{rad * 0.84:.0f}"/>'
            f'<circle cx="{W_ / 2 + rad * 0.5:.0f}" cy="{cy}" r="{rad * 0.84:.0f}"/>'
        )
    else:  # medallion
        eng_cx, eng_cy, eng_r = W_ / 2, cy, rad
        clip_shape = f'<circle cx="{W_ / 2}" cy="{cy}" r="{rad}"/>'
    eng_defs, eng_body = _ENGRAVERS[engraving](eng_cx, eng_cy, eng_r, seed, petals, inner)

    p = [
        "<defs>",
        f'<clipPath id="cut">{clip_shape}</clipPath>',
        eng_defs,
        f'<linearGradient id="plate" x1="0.1" y1="0" x2="0.85" y2="1">'
        f'<stop offset="0" stop-color="{field}"/>'
        f'<stop offset="0.62" stop-color="{field2}"/>'
        f'<stop offset="1" stop-color="{edge_col}"/></linearGradient>',
        f'<radialGradient id="bloom" cx="0.5" cy="0.5" r="0.5">'
        f'<stop offset="0" stop-color="{accent}" stop-opacity="{0.16 if proof else 0.20}"/>'
        f'<stop offset="0.5" stop-color="{sector_col}" stop-opacity="{0.08 if proof else 0.09}"/>'
        f'<stop offset="1" stop-color="{sector_col}" stop-opacity="0"/></radialGradient>',
        f'<radialGradient id="clear" cx="0.5" cy="0.5" r="0.5">'
        f'<stop offset="0" stop-color="{b["bg"] if proof else field2}" stop-opacity="0.90"/>'
        f'<stop offset="0.6" stop-color="{b["bg"] if proof else field2}" stop-opacity="0.74"/>'
        f'<stop offset="1" stop-color="{b["bg"] if proof else field2}" '
        f'stop-opacity="0"/></radialGradient>',
        f'<pattern id="hatch" width="7" height="7" patternUnits="userSpaceOnUse" '
        f'patternTransform="rotate(35)">'
        f'<line x1="0" y1="0" x2="0" y2="7" stroke="{"#000000" if proof else "#ffffff"}" '
        f'stroke-opacity="0.030" stroke-width="1"/></pattern>',
        f'<linearGradient id="span" x1="0" y1="0" x2="1" y2="0">'
        f'<stop offset="0" stop-color="{hero_col}" stop-opacity="0.10"/>'
        f'<stop offset="1" stop-color="{hero_col}" stop-opacity="0.55"/></linearGradient>',
        f'<path id="gs" d="{_guilloche(W_ - 200, 1082, 52, petals + 2, inner * 0.8, 140)}"/>',
        f'<path id="sealArc" d="M{W_ - 258} 1082 A58 58 0 0 1 {W_ - 142} 1082" fill="none"/>',
        "</defs>",
        f'<rect width="{W_}" height="{H_}" fill="url(#plate)"/>',
        f'<rect width="{W_}" height="{H_}" fill="url(#hatch)"/>',
        f'<ellipse cx="{eng_cx}" cy="{eng_cy}" rx="{eng_r + 150}" ry="{eng_r + 140}" '
        f'fill="url(#bloom)"/>',
    ]

    # ── the engraving ───────────────────────────────────────────────────────
    # Stroke weights are set for the THUMBNAIL. At 0.7px on a 1000px plate an
    # engraving resolves to 0.13px in a 190px grid cell and simply vanishes.
    if eng_body.startswith("__PATTERN__"):
        pid = eng_body[len("__PATTERN__") :]
        p.append(
            f'<g clip-path="url(#cut)" color="{rim}" opacity="0.60">'
            f'<rect width="{W_}" height="{H_}" fill="url(#{pid})"/></g>'
        )
    else:
        dash = ' stroke-dasharray="5 6"' if ink == "stipple" else ""
        p.append(
            f'<g clip-path="url(#cut)" stroke="{rim}" fill="none" stroke-width="2.2" '
            f'opacity="0.58"{dash}>{eng_body}</g>'
        )
        if ink == "double":
            # The same cut struck again off-register, the way a second pass on
            # the lathe reads.
            p.append(
                f'<g clip-path="url(#cut)" stroke="{sector_col}" fill="none" '
                f'stroke-width="1.1" opacity="0.40" transform="translate(3 3)">{eng_body}</g>'
            )

    # ── ruled border, struck in the tier metal ──────────────────────────────
    # Weight steps with the tier as well as hue — at 190px a hue shift alone
    # does not separate platinum from graphite, but a heavier rule does.
    frame_w = {"Founder": 4.5, "Early": 3.5}.get(badge, 2.5)
    p.append(
        f'<rect x="{PL}" y="{PT}" width="{PR - PL}" height="{PB - PT}" fill="none" '
        f'stroke="{metal}" stroke-opacity="0.85" stroke-width="{frame_w}"/>'
        f'<rect x="{PL + 11}" y="{PT + 11}" width="{PR - PL - 22}" height="{PB - PT - 22}" '
        f'fill="none" stroke="{metal}" stroke-opacity="0.30" stroke-width="1.2"/>'
    )
    for cx_, cy_ in (
        (PL + 11, PT + 11),
        (PR - 11, PT + 11),
        (PL + 11, PB - 11),
        (PR - 11, PB - 11),
    ):
        p.append(
            f'<circle cx="{cx_}" cy="{cy_}" r="17" fill="none" stroke="{metal}" '
            f'stroke-opacity="0.5" stroke-width="1.6"/>'
            f'<circle cx="{cx_}" cy="{cy_}" r="7" fill="{metal}" fill-opacity="0.55"/>'
        )

    # ── head ────────────────────────────────────────────────────────────────
    p.append(_small_caps("Suwappu", IL, 118, 16, mark_col, 7.0, "bold"))
    p.append(
        _small_caps(
            "Certificate of Position",
            W_ / 2,
            118,
            11.5,
            _mix(rim, body_col, 0.30),
            4.0,
            anchor="middle",
        )
    )
    p.append(
        f'<text x="{IR}" y="118" font-family="{SERIF}" font-size="18" fill="{metal}" '
        f'text-anchor="end" letter-spacing="1.4">{esc(f"No. {rank:04d}")}</text>'
    )
    p.append(
        f'<line x1="{IL}" y1="140" x2="{IR}" y2="140" stroke="{metal}" '
        f'stroke-opacity="0.45" stroke-width="1.2"/>'
    )

    # ── ticker: at 190px this and one number ARE the card ───────────────────
    tsize = 150 if len(ticker) <= 4 else (124 if len(ticker) == 5 else 104)
    p.append(
        f'<text x="{IL}" y="290" font-family="{SERIF}" font-size="{tsize}" font-weight="bold" '
        f'fill="{body_col}" letter-spacing="-3">{esc(ticker)}</text>'
    )
    if len(company) <= 40:
        name = company
    else:
        cut = company[:40].rsplit(" ", 1)[0]
        name = (cut if len(cut) > 18 else company[:39]) + "\u2026"
    p.append(_small_caps(name, IL, 330, 14.5, _mix(sector_col, body_col, 0.45), 3.2))
    p.append(_small_caps(sector, IL, 360, 12, _mix(sector_col, body_col, 0.20), 3.4))
    if badge:
        # The tier, set in its own metal — gold reads as gold even at 190px.
        p.append(_small_caps(badge, IR, 282, 21, metal, 5.5, "bold", anchor="end"))
        p.append(
            f'<line x1="{IR - 150}" y1="298" x2="{IR}" y2="298" stroke="{metal}" '
            f'stroke-opacity="0.6" stroke-width="1.6"/>'
        )

    # ── the two real numbers ────────────────────────────────────────────────
    # Proportional to the rosette, not offset from it. At rad+60 x rad-30 a
    # low-magnitude plate had its entire engraving covered — every losing card
    # in the grid read as a dark smudge with one faint ring left showing. This
    # clears the middle band where the numeral sits and leaves the outer rings.
    p.append(
        f'<ellipse cx="{W_ / 2}" cy="{cy}" rx="{rad * 0.88:.0f}" ry="{rad * 0.5:.0f}" '
        f'fill="url(#clear)"/>'
    )
    if priced:
        sign = "+" if ret_bps >= 0 else "\u2212"
        hero = f"{sign}{abs(ret_bps) / 100:,.1f}%"
        hsize = 138 if len(hero) <= 6 else (120 if len(hero) <= 7 else 104)
        p.append(
            f'<text x="{W_ / 2}" y="{cy + 44}" font-family="{SERIF}" font-size="{hsize}" '
            f'font-weight="bold" fill="{hero_col}" text-anchor="middle" '
            f'letter-spacing="-3">{esc(hero)}</text>'
        )
        p.append(
            _small_caps(
                "since entry",
                W_ / 2,
                cy + 84,
                12,
                _mix(hero_col, body_col, 0.35),
                6.0,
                anchor="middle",
            )
        )
    else:
        p.append(
            f'<text x="{W_ / 2}" y="{cy + 26}" font-family="{SERIF}" font-size="82" '
            f'fill="#a09889" text-anchor="middle" font-style="italic" '
            f'letter-spacing="2">Unpriced</text>'
        )
        p.append(
            _small_caps("no basis stamped", W_ / 2, cy + 70, 12, "#7a7367", 5.0, anchor="middle")
        )

    # ── basis -> now, engraved. One band, not four. ─────────────────────────
    sy = 952
    rule = _mix(rim, body_col, 0.28)
    p.append(f'<line x1="{IL}" y1="{sy}" x2="{IR}" y2="{sy}" stroke="{rule}" stroke-width="1.4"/>')
    if priced:
        for k in range(1, 20):
            tx = IL + (IR - IL) * k / 20.0
            tall = 10 if k % 5 == 0 else 5
            p.append(
                f'<line x1="{tx:.1f}" y1="{sy - tall}" x2="{tx:.1f}" y2="{sy + tall}" '
                f'stroke="{rule}" stroke-opacity="0.7" stroke-width="1.1"/>'
            )
        e_x = IL if price >= entry else IR
        n_x = IR if price >= entry else IL
        # Pivot on the rect's own centre — rotating about y=0 threw the whole
        # band off-canvas, so every losing card lost its gradient bar.
        flip = f' transform="rotate(180 500 {sy})"' if n_x < e_x else ""
        p.append(
            f'<rect x="{min(e_x, n_x)}" y="{sy - 17}" width="{abs(n_x - e_x)}" height="34" '
            f'fill="url(#span)"{flip}/>'
        )
        for xx, lab, val, col in (
            (e_x, "basis", fmt_px(entry), quiet),
            (n_x, "now", fmt_px(price), hero_col),
        ):
            anc = "start" if xx < W_ / 2 else "end"
            p.append(
                f'<line x1="{xx}" y1="{sy - 26}" x2="{xx}" y2="{sy + 26}" stroke="{col}" '
                f'stroke-width="3"/>'
            )
            p.append(_small_caps(lab, xx, sy - 38, 11, quiet, 4.0, anchor=anc))
            p.append(
                f'<text x="{xx}" y="{sy + 60}" font-family="{SERIF}" font-size="34" '
                f'fill="{col}" text-anchor="{anc}">${esc(val)}</text>'
            )

    # ── seal — outer ring in the tier metal, grade in its accent ────────────
    scx, scy, sr = W_ - 200, 1082, 72
    p.append(
        f'<circle cx="{scx}" cy="{scy}" r="{sr}" fill="{edge_col}" fill-opacity="0.75"/>'
        f'<circle cx="{scx}" cy="{scy}" r="{sr}" fill="none" stroke="{metal}" '
        f'stroke-opacity="0.85" stroke-width="2.6"/>'
        f'<circle cx="{scx}" cy="{scy}" r="{sr - 10}" fill="none" stroke="{accent}" '
        f'stroke-opacity="0.35" stroke-width="1"/>'
    )
    p.append(f'<g stroke="{accent}" fill="none" stroke-width="1" opacity="0.32">')
    for i in range(5):
        p.append(f'<use href="#gs" transform="rotate({spin + i * 72:.1f} {scx} {scy})"/>')
    p.append("</g>")
    p.append(
        f'<text font-family="{MONO}" font-size="11" fill="{accent}" fill-opacity="0.9" '
        f'letter-spacing="3.4"><textPath href="#sealArc" startOffset="50%" '
        f'text-anchor="middle">{esc(grade["name"].upper())}</textPath></text>'
    )
    p.append(
        f'<text x="{scx}" y="{scy + 12}" font-family="{SERIF}" font-size="30" '
        f'font-weight="bold" fill="{body_col}" text-anchor="middle">{esc(ticker[:4])}</text>'
    )

    # ── one footing band, not four ──────────────────────────────────────────
    struck = minted_at.strftime("%d %b %Y").upper() if minted_at else "\u2014"
    # Small caps, no minus sign: set as "\u221240%" under the P&L numeral this line
    # scanned as a second, negative return at thumbnail size.
    p.append(_small_caps(f"{disc_pct}% off every swap", IL, 1070, 20, body_col, 4.5, "bold"))
    p.append(
        _small_caps(
            f"struck {struck} \u00b7 rank {rank} of {cfg['collection']['supply']:,}",
            IL,
            1104,
            11.5,
            quiet,
            3.0,
        )
    )
    p.append(
        _small_caps(
            "collectible \u00b7 not equity \u00b7 not a security \u00b7 pays nothing \u00b7 "
            "no claim on any issuer",
            IL,
            PB - 26,
            9.5,
            faint,
            2.2,
        )
    )
    p.append(_small_caps(f"4663 \u00b7 {token_id}", IR, PB - 26, 9.5, faint, 2.2, anchor="end"))

    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W_}" height="{H_}" '
        f'viewBox="0 0 {W_} {H_}" role="img" aria-label="{esc(ticker)} position card">'
        + "".join(p)
        + "</svg>"
    )


def build_metadata(cfg, registry, token_id, ticker, entry, price, rank, minted_at=None):
    """ERC-721 metadata for a live position. Regenerated on every fetch — the
    return and grade move with the market, so this is deliberately dynamic."""
    addr, decimals, company = registry[ticker]
    priced = bool(entry and price and entry > 0)
    ret_bps = int(round((price - entry) / entry * 10_000)) if priced else 0
    grade = grade_for(cfg, ret_bps) if priced else {"name": "Unpriced"}
    col = cfg["collection"]
    badge = badge_for(cfg, rank)

    attrs = [
        {"trait_type": "Ticker", "value": ticker},
        {"trait_type": "Company", "value": company},
        {"trait_type": "Sector", "value": sector_of(cfg, ticker)},
        {"trait_type": "Grade", "value": grade["name"]},
        {"trait_type": "Mint Rank", "value": rank, "display_type": "number"},
    ]
    if badge:
        attrs.append({"trait_type": "Badge", "value": badge})
    if priced:
        attrs += [
            {"trait_type": "Entry Price", "value": round(entry, 4)},
            {
                "trait_type": "Return %",
                "value": round(ret_bps / 100.0, 2),
                "display_type": "number",
            },
        ]
    if minted_at:
        attrs.append(
            {
                "trait_type": "Held Since",
                "value": int(minted_at.timestamp()),
                "display_type": "date",
            }
        )

    if priced:
        desc = (
            f"A position on {company} ({ticker}) opened on Robinhood Chain at "
            f"${fmt_px(entry)}. Currently ${fmt_px(price)} — "
            f"{'up' if ret_bps >= 0 else 'down'} {abs(ret_bps) / 100:.1f}%. "
            f"Mint rank {rank} of 10,000.\n\n"
            f"The entry price was stamped on-chain at mint and can never change; the "
            f"card re-renders against the live price, so what you see is the call you "
            f"actually made. Holding it takes "
            f"{int(round(cfg['economics']['hold_discount_fraction'] * 100))}% off your "
            f"Suwappu swap fee on the Free, Pro and Premium plans (Enterprise pricing "
            f"is contracted separately).\n\n"
            f"{col['compliance']}"
        )
    else:
        desc = (
            f"A position on {company} ({ticker}) on Robinhood Chain, minted while no "
            f"oracle price was available, so no entry basis was stamped and no return "
            f"is tracked. Mint rank {rank} of 10,000.\n\n{col['compliance']}"
        )

    return {
        "name": (f"{ticker} #{rank}" + (f" · {grade['name']}" if priced else " · Unpriced")),
        "description": desc,
        "image": f"{col['external_url']}/card/{token_id}.svg",
        "external_url": f"{col['external_url']}/{token_id}",
        "attributes": attrs,
        "properties": {
            "chain_id": col["chain"]["chain_id"],
            "underlying_erc20": addr,
            "underlying_decimals": decimals,
            "disclaimer": col["compliance"],
        },
    }


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--gallery", action="store_true")
    ap.add_argument("--ticker", default="NVDA")
    ap.add_argument("--entry", type=float, default=100.0)
    ap.add_argument("--price", type=float, default=137.0)
    ap.add_argument("--rank", type=int, default=42)
    ap.add_argument("--out", default=os.path.join(HERE, "preview"))
    args = ap.parse_args()

    cfg, registry = load_config(), load_registry()
    os.makedirs(args.out, exist_ok=True)

    if args.gallery:
        # Current prices are the REAL values read from the Chainlink feeds on
        # chain 4663 (see feeds.json / verify_feeds.py). Entries are illustrative
        # basis points in time, since nothing has been minted yet.
        feeds = json.load(open(os.path.join(HERE, "feeds.json")))["feeds"]
        samples = [
            ("NVDA", 0.42, 1),
            ("SPCX", 0.28, 318),
            ("AAPL", 1.06, 1804),
            ("IONQ", 1.19, 5522),
            ("GME", 1.55, 9310),
            ("TSLA", None, 7781),
        ]
        for i, (tk, ratio, rank) in enumerate(samples, start=1):
            price = feeds[tk]["verified_price_usd"]
            entry = round(price * ratio, 2) if ratio else None
            minted = datetime(2026, 8, 1 + (i % 12), 9, 0, tzinfo=timezone.utc)
            svg = render_card(cfg, registry, i, tk, entry, price if ratio else None, rank, minted)
            open(os.path.join(args.out, f"{tk}.svg"), "w").write(svg)
        print(f"gallery -> {args.out} (current prices are live feed values)")
    else:
        svg = render_card(cfg, registry, 1, args.ticker, args.entry, args.price, args.rank)
        path = os.path.join(args.out, f"{args.ticker}.svg")
        open(path, "w").write(svg)
        print(path)
