// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/utils/Strings.sol";

/**
 * @title SuwappuFills — 10,000 order tickets from the Robinhood Chain tape
 *
 * Target: Robinhood Chain (chain id 4663, Arbitrum Orbit / Nitro, native gas ETH).
 *         Testnet: 46630.
 *
 * Each ticket is a filled order for one of the ~96 canonical tokenized equities
 * that trade as ordinary ERC-20s on chain 4663. Art + metadata are generated by
 * nft/fills/generate.py, whose ticker universe is read directly from
 * bot/config/tokens.py::ROBINHOOD_EQUITIES (the on-chain-verified registry).
 *
 * Three properties this contract is built around:
 *
 *  1. FAIR ASSIGNMENT. The provenance hash commits the image set before mint, and
 *     `startingIndex` — drawn from a future block hash — rotates token ids onto
 *     asset ids. Without the rotation a provenance hash proves nothing about who
 *     gets what, since asset N would always land on token N.
 *
 *  2. ON-CHAIN TRAITS. Suwappu grants a swap-fee discount and a per-ticker XP
 *     boost for holding a ticket. The bot must not have to trust an off-chain
 *     JSON file for that, so the (ticker, desk) pair for all 10,000 assets is
 *     stored on-chain as a packed 20,000-byte blob, uploaded in batches and
 *     sealed against an immutable keccak256 commitment.
 *
 *  3. NO EQUITY SEMANTICS. A ticket is a collectible referencing an ERC-20. It
 *     conveys no equity, no shareholder rights, and no claim on any issuer — see
 *     the compliance note in bot/config/tokens.py.
 */
contract SuwappuFills is ERC721, Ownable, ReentrancyGuard {
    using Strings for uint256;

    uint256 public constant MAX_SUPPLY = 10_000;
    uint256 public constant MAX_PER_WALLET = 20;
    uint256 public constant TICKER_COUNT = 96;
    uint256 public constant DESK_COUNT = 5;
    /// @dev Blocks between commit and reveal. Arbitrum keeps 256 recent block
    ///      hashes like L1, so the draw must be claimed inside that window.
    uint256 public constant REVEAL_DELAY = 20;

    /// @notice sha256 over the committed image set (nft/fills/provenance.json).
    bytes32 public immutable provenanceHash;
    /// @notice keccak256 of the full packed traits blob (MAX_SUPPLY * 2 bytes).
    bytes32 public immutable traitsCommitment;

    /// @notice Fee discount in basis points per desk index, applied to the
    ///         Suwappu swap fee. Index order matches nft/fills/config.json.
    ///         Retail, Desk, Prime, Whale, House.
    uint16[5] public deskDiscountBps = [uint16(5), 10, 20, 35, 50];

    uint256 public totalSupply;
    uint256 public mintPrice;
    bool public mintOpen;
    bool public metadataFrozen;

    /// @notice Packed traits: 2 bytes per asset id — [tickerIndex, deskIndex].
    bytes private _packedTraits;
    bool public traitsSealed;

    uint256 public revealBlock;
    uint256 public startingIndex;
    bool public startingIndexSet;

    string private _baseTokenURI;
    string private _unrevealedURI;
    mapping(address => uint256) public minted;

    event MintOpenSet(bool open);
    event MintPriceSet(uint256 price);
    event BaseURISet(string baseURI);
    event MetadataFrozen();
    event TraitsSealed(uint256 assets);
    event RevealCommitted(uint256 revealBlock);
    event StartingIndexSet(uint256 startingIndex);

    error MintClosed();
    error SoldOut();
    error WalletLimitExceeded();
    error WrongPayment();
    error MetadataIsFrozen();
    error ZeroQuantity();
    error TraitsAlreadySealed();
    error TraitsNotSealed();
    error TraitsLengthMismatch();
    error TraitsCommitmentMismatch();
    error AlreadyCommitted();
    error AlreadyDrawn();
    error NotCommitted();
    error TooEarly();
    error UnknownToken();
    error NotOwner();

    constructor(
        string memory unrevealedURI,
        bytes32 provenance,
        bytes32 traitsCommit,
        address initialOwner
    ) ERC721("Suwappu Fills", "FILL") Ownable(initialOwner) {
        _unrevealedURI = unrevealedURI;
        provenanceHash = provenance;
        traitsCommitment = traitsCommit;
    }

    // ─── Mint ─────────────────────────────────────────────────────────────────

    function mint(uint256 quantity) external payable nonReentrant {
        if (!mintOpen) revert MintClosed();
        if (quantity == 0) revert ZeroQuantity();
        if (totalSupply + quantity > MAX_SUPPLY) revert SoldOut();
        if (minted[msg.sender] + quantity > MAX_PER_WALLET) revert WalletLimitExceeded();
        if (msg.value != mintPrice * quantity) revert WrongPayment();

        minted[msg.sender] += quantity;
        uint256 first = totalSupply + 1;
        totalSupply += quantity;
        for (uint256 i = 0; i < quantity; i++) {
            _safeMint(msg.sender, first + i);
        }
    }

    /// @notice Treasury / airdrop mint. Same supply cap, exempt from the wallet limit.
    function ownerMint(address to, uint256 quantity) external onlyOwner {
        if (quantity == 0) revert ZeroQuantity();
        if (totalSupply + quantity > MAX_SUPPLY) revert SoldOut();
        uint256 first = totalSupply + 1;
        totalSupply += quantity;
        for (uint256 i = 0; i < quantity; i++) {
            _safeMint(to, first + i);
        }
    }

    // ─── Fair assignment ──────────────────────────────────────────────────────

    /// @notice Commit to drawing the starting index from a specific future block.
    ///         Callable once; the hash of `revealBlock` is not knowable now.
    function commitReveal() external onlyOwner {
        if (revealBlock != 0) revert AlreadyCommitted();
        revealBlock = block.number + REVEAL_DELAY;
        emit RevealCommitted(revealBlock);
    }

    /// @notice Draw the starting index. Permissionless once the committed block is
    ///         mined, so the owner cannot stall a draw they dislike.
    /// @dev    `blockhash` returns 0 for blocks more than 256 deep. If the window is
    ///         missed the draw falls back to the previous block hash — still outside
    ///         the owner's control, and re-committing is not possible.
    function drawStartingIndex() external {
        if (revealBlock == 0) revert NotCommitted();
        if (startingIndexSet) revert AlreadyDrawn();
        if (block.number <= revealBlock) revert TooEarly();

        bytes32 bh = blockhash(revealBlock);
        if (bh == bytes32(0)) bh = blockhash(block.number - 1);

        uint256 idx = uint256(bh) % MAX_SUPPLY;
        if (idx == 0) idx = 1; // never an identity mapping
        startingIndex = idx;
        startingIndexSet = true;
        emit StartingIndexSet(idx);
    }

    /// @notice Asset id (the generated ticket) backing a given token id.
    function assetIdOf(uint256 tokenId) public view returns (uint256) {
        if (tokenId == 0 || tokenId > MAX_SUPPLY) revert UnknownToken();
        if (!startingIndexSet) revert TooEarly();
        return ((tokenId - 1 + startingIndex) % MAX_SUPPLY) + 1;
    }

    // ─── On-chain traits ──────────────────────────────────────────────────────

    /// @notice Append a chunk of the packed traits blob (2 bytes per asset id,
    ///         ordered by asset id: [tickerIndex, deskIndex]).
    function appendTraits(bytes calldata chunk) external onlyOwner {
        if (traitsSealed) revert TraitsAlreadySealed();
        _packedTraits = bytes.concat(_packedTraits, chunk);
    }

    /// @notice Seal the blob once complete. Verifies length and the immutable
    ///         keccak256 commitment, so the stored traits provably match the
    ///         generated collection and can never be edited afterwards.
    function sealTraits() external onlyOwner {
        if (traitsSealed) revert TraitsAlreadySealed();
        if (_packedTraits.length != MAX_SUPPLY * 2) revert TraitsLengthMismatch();
        if (keccak256(_packedTraits) != traitsCommitment) revert TraitsCommitmentMismatch();
        traitsSealed = true;
        emit TraitsSealed(MAX_SUPPLY);
    }

    function traitsLength() external view returns (uint256) {
        return _packedTraits.length;
    }

    /// @return tickerIndex Index into ROBINHOOD_EQUITIES sorted by symbol (0..95).
    /// @return deskIndex   0=Retail 1=Desk 2=Prime 3=Whale 4=House.
    function traitsOf(uint256 tokenId)
        public
        view
        returns (uint8 tickerIndex, uint8 deskIndex)
    {
        if (!traitsSealed) revert TraitsNotSealed();
        uint256 assetId = assetIdOf(tokenId);
        uint256 o = (assetId - 1) * 2;
        return (uint8(_packedTraits[o]), uint8(_packedTraits[o + 1]));
    }

    /// @notice Swap-fee discount in bps this ticket grants its holder.
    function feeDiscountBps(uint256 tokenId) public view returns (uint16) {
        (, uint8 desk) = traitsOf(tokenId);
        return deskDiscountBps[desk];
    }

    /// @notice Best discount across `tokenIds` actually owned by `owner`.
    ///         A view — the bot passes the holdings it read from an indexer and
    ///         gets back a number it can verify on-chain. Tokens not owned by
    ///         `owner` are ignored rather than reverting, so a stale indexer
    ///         result degrades to a smaller discount instead of a failed swap.
    function bestDiscountBps(address owner, uint256[] calldata tokenIds)
        external
        view
        returns (uint16 best)
    {
        for (uint256 i = 0; i < tokenIds.length; i++) {
            uint256 id = tokenIds[i];
            if (_ownerOf(id) != owner) continue;
            uint16 d = feeDiscountBps(id);
            if (d > best) best = d;
        }
    }

    /// @notice Whether `owner` holds a ticket for `tickerIndex` (drives the
    ///         per-ticker XP boost on that equity's swaps).
    function holdsTicker(address owner, uint256[] calldata tokenIds, uint8 tickerIndex)
        external
        view
        returns (bool)
    {
        for (uint256 i = 0; i < tokenIds.length; i++) {
            uint256 id = tokenIds[i];
            if (_ownerOf(id) != owner) continue;
            (uint8 t,) = traitsOf(id);
            if (t == tickerIndex) return true;
        }
        return false;
    }

    // ─── Admin ────────────────────────────────────────────────────────────────

    function setMintOpen(bool open) external onlyOwner {
        mintOpen = open;
        emit MintOpenSet(open);
    }

    function setMintPrice(uint256 price) external onlyOwner {
        mintPrice = price;
        emit MintPriceSet(price);
    }

    function setBaseURI(string calldata baseURI) external onlyOwner {
        if (metadataFrozen) revert MetadataIsFrozen();
        _baseTokenURI = baseURI;
        emit BaseURISet(baseURI);
    }

    function freezeMetadata() external onlyOwner {
        metadataFrozen = true;
        emit MetadataFrozen();
    }

    function withdraw(address payable to) external onlyOwner nonReentrant {
        (bool ok,) = to.call{ value: address(this).balance }("");
        require(ok, "withdraw failed");
    }

    // ─── Views ────────────────────────────────────────────────────────────────

    /// @dev Resolves to the ASSET id, not the token id, so the starting-index
    ///      rotation actually determines which ticket a token shows.
    function tokenURI(uint256 tokenId) public view override returns (string memory) {
        _requireOwned(tokenId);
        if (!startingIndexSet || bytes(_baseTokenURI).length == 0) {
            return _unrevealedURI;
        }
        return string.concat(_baseTokenURI, assetIdOf(tokenId).toString());
    }
}
