// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { Script, console } from "forge-std/Script.sol";
import { SuwappuPositions } from "../SuwappuPositions.sol";
import { RobinhoodChainlinkOracle } from "../RobinhoodChainlinkOracle.sol";

/**
 * @title DeployPositions — Suwappu Positions + its Chainlink oracle on Robinhood Chain
 *
 * Robinhood Chain (Arbitrum Orbit, native gas ETH):
 *   Mainnet: chain id 4663,  explorer https://robinhoodchain.blockscout.com
 *   Testnet: chain id 46630, faucet https://faucet.testnet.chain.robinhood.com
 *
 * Args come from nft/position-cards/deploy_args.json, generated by
 *   python3 nft/position-cards/build_deploy_args.py
 * and read here with vm.parseJson rather than pasted, so the on-chain ticker order
 * can never drift from the order the bot resolves.
 *
 * This script deploys BOTH contracts and wires them, because a Positions deploy
 * without a live oracle stamps entryPrice = 0 on every early mint — permanently.
 *
 * NOTE: the Chainlink feed addresses in deploy_args.json are MAINNET (4663) feeds,
 * verified live. They do not exist on the testnet, so a testnet run will register
 * feeds that return nothing and every card will read as UNPRICED. That is expected
 * and is exactly what the unpriced path is for.
 *
 * Usage:
 *   export DEPLOYER_PRIVATE_KEY=0x...
 *   export POSITIONS_RENDER_URI=https://suwappu.bot/positions/meta/
 *   # optional, once Chainlink publishes it for chain 4663:
 *   export SEQUENCER_UPTIME_FEED=0x...
 *   forge script contracts/deploy/DeployPositions.s.sol \
 *     --rpc-url https://rpc.mainnet.chain.robinhood.com --broadcast -vvvv
 */
contract DeployPositions is Script {
    uint256 constant N = 35;

    function run() external {
        uint256 pk = vm.envUint("DEPLOYER_PRIVATE_KEY");
        address deployer = vm.addr(pk);
        string memory renderURI = vm.envString("POSITIONS_RENDER_URI");
        address sequencer = vm.envOr("SEQUENCER_UPTIME_FEED", address(0));

        require(
            block.chainid == 4663 || block.chainid == 46630,
            "wrong chain: expected Robinhood Chain (4663) or its testnet (46630)"
        );

        string memory json = vm.readFile("nft/position-cards/deploy_args.json");
        uint256[] memory rawCaps = vm.parseJsonUintArray(json, ".caps");
        address[] memory rawTokens = vm.parseJsonAddressArray(json, ".tokens");
        address[] memory rawAggs = vm.parseJsonAddressArray(json, ".aggregators");
        require(
            rawCaps.length == N && rawTokens.length == N && rawAggs.length == N,
            "deploy_args must have 35 entries per array"
        );

        uint16[35] memory caps;
        address[35] memory tokens;
        uint256 sum;
        for (uint256 i = 0; i < N; i++) {
            require(rawCaps[i] > 0 && rawCaps[i] <= type(uint16).max, "cap out of range");
            require(rawTokens[i] != address(0) && rawAggs[i] != address(0), "zero address");
            caps[i] = uint16(rawCaps[i]);
            tokens[i] = rawTokens[i];
            sum += rawCaps[i];
        }
        require(sum == 4_444, "caps must sum to 4444");

        vm.startBroadcast(pk);

        RobinhoodChainlinkOracle oracle = new RobinhoodChainlinkOracle(deployer);
        oracle.setFeeds(rawTokens, rawAggs);
        if (sequencer != address(0)) {
            oracle.setSequencerUptimeFeed(sequencer);
        }
        oracle.sealFeeds(N);

        SuwappuPositions pos = new SuwappuPositions(caps, tokens, renderURI, deployer);
        pos.setOracle(address(oracle));
        pos.sealRegistry();

        vm.stopBroadcast();

        console.log("RobinhoodChainlinkOracle:", address(oracle));
        console.log("SuwappuPositions:", address(pos));
        console.log("chain id:", block.chainid);
        console.log("sequencer uptime feed:", sequencer);
        console.log("next: setEthUsdFeed(0x78F3556b67E17Df817D51Ef5a990cDaF09E8d3A9)");
        console.log("      setFallbackWeiPerUsdCent(...)  // used only if the feed is stale");
        console.log("      configurePhase() per phase - price is USD CENTS, not wei (Gold too, index 4)");
        console.log("      default royalty is already 2% (200 bps), set in the constructor;");
        console.log("      setTreasury(...) re-points royalties automatically (receiver follows");
        console.log("      treasury); setDefaultRoyalty(receiver, bps) only if retuning the rate");
        console.log("      announceEnd(...) then closeMintingForever() when done");
        console.log("  roots come from: python3 nft/position-cards/build_allowlist.py --from-db");
        console.log("sanity: oracle.debugPrice(<token>) should return a non-zero price1e18");
    }
}
