import { useState } from 'react'
import type { Meta, StoryObj } from '@storybook/react'
import {
  SwapHistory,
  type SwapHistoryProps,
  type SwapHistoryEntry,
  type ChainFilter,
  type StatusFilter,
} from '../../components/swap/SwapHistory'

const meta = {
  title: 'Swap/SwapHistory',
  component: SwapHistory,
  parameters: {
    layout: 'padded',
  },
  tags: ['autodocs'],
  argTypes: {
    isLoading: { control: 'boolean' },
    chainFilter: { control: 'text' },
    statusFilter: { control: 'select', options: ['all', 'completed', 'pending', 'failed'] },
  },
} satisfies Meta<typeof SwapHistory>

export default meta
type Story = StoryObj<typeof meta>

// --- Mock Data ---

const now = Date.now()
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString()
const daysAgo = (d: number) => new Date(now - d * 86_400_000).toISOString()

const mockEntries: SwapHistoryEntry[] = [
  {
    id: '1',
    fromToken: { symbol: 'ETH' },
    toToken: { symbol: 'USDC' },
    fromChain: 'ethereum',
    toChain: 'ethereum',
    fromAmount: 0.5,
    toAmount: 622.83,
    fromAmountUsd: 615,
    toAmountUsd: 622.83,
    status: 'completed',
    provider: 'CoW Protocol',
    txHash: '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef',
    explorerUrl: 'https://etherscan.io/tx/0x1234',
    pnl: 12.34,
    pnlPercent: 0.5,
    createdAt: hoursAgo(2),
    completedAt: hoursAgo(1.99),
  },
  {
    id: '2',
    fromToken: { symbol: 'USDC' },
    toToken: { symbol: 'ARB' },
    fromChain: 'arbitrum',
    toChain: 'arbitrum',
    fromAmount: 500,
    toAmount: 420.5,
    fromAmountUsd: 500,
    toAmountUsd: 504.6,
    status: 'completed',
    provider: 'Uniswap V3',
    txHash: '0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890',
    explorerUrl: 'https://arbiscan.io/tx/0xabcdef',
    pnl: 4.6,
    pnlPercent: 0.92,
    createdAt: hoursAgo(5),
    completedAt: hoursAgo(4.99),
  },
  {
    id: '3',
    fromToken: { symbol: 'SOL' },
    toToken: { symbol: 'BONK' },
    fromChain: 'solana',
    toChain: 'solana',
    fromAmount: 2.5,
    toAmount: 8_500_000,
    fromAmountUsd: 350,
    toAmountUsd: 340,
    status: 'completed',
    provider: 'Jupiter',
    txHash: '5KtPn1LGuxhG...',
    explorerUrl: 'https://solscan.io/tx/5KtPn1',
    pnl: -10,
    pnlPercent: -2.86,
    createdAt: hoursAgo(18),
    completedAt: hoursAgo(17.99),
  },
  {
    id: '4',
    fromToken: { symbol: 'ETH' },
    toToken: { symbol: 'USDC' },
    fromChain: 'ethereum',
    toChain: 'arbitrum',
    fromAmount: 1.0,
    toAmount: 1245.5,
    fromAmountUsd: 1230,
    toAmountUsd: 1245.5,
    status: 'pending',
    provider: 'Across',
    txHash: '0xpending123456789...',
    createdAt: hoursAgo(0.1),
  },
  {
    id: '5',
    fromToken: { symbol: 'MATIC' },
    toToken: { symbol: 'USDT' },
    fromChain: 'polygon',
    toChain: 'polygon',
    fromAmount: 1000,
    toAmount: 0,
    fromAmountUsd: 850,
    toAmountUsd: 0,
    status: 'failed',
    provider: 'QuickSwap',
    txHash: '0xfailed987654321...',
    explorerUrl: 'https://polygonscan.com/tx/0xfailed',
    createdAt: daysAgo(1),
  },
  {
    id: '6',
    fromToken: { symbol: 'WETH' },
    toToken: { symbol: 'DAI' },
    fromChain: 'base',
    toChain: 'base',
    fromAmount: 0.3,
    toAmount: 370.25,
    fromAmountUsd: 369,
    toAmountUsd: 370.25,
    status: 'completed',
    provider: 'Aerodrome',
    txHash: '0xbase1234...',
    explorerUrl: 'https://basescan.org/tx/0xbase1234',
    pnl: 1.25,
    pnlPercent: 0.34,
    createdAt: daysAgo(2),
    completedAt: new Date(new Date(daysAgo(2)).getTime() + 8000).toISOString(),
  },
  {
    id: '7',
    fromToken: { symbol: 'ETH' },
    toToken: { symbol: 'OP' },
    fromChain: 'optimism',
    toChain: 'optimism',
    fromAmount: 0.15,
    toAmount: 105.3,
    fromAmountUsd: 184.5,
    toAmountUsd: 189.54,
    status: 'completed',
    provider: 'Velodrome',
    txHash: '0xoptimism5678...',
    explorerUrl: 'https://optimistic.etherscan.io/tx/0xoptimism5678',
    pnl: 5.04,
    pnlPercent: 2.73,
    createdAt: daysAgo(3),
    completedAt: new Date(new Date(daysAgo(3)).getTime() + 12000).toISOString(),
  },
  {
    id: '8',
    fromToken: { symbol: 'AVAX' },
    toToken: { symbol: 'USDC' },
    fromChain: 'avalanche',
    toChain: 'avalanche',
    fromAmount: 10,
    toAmount: 352.1,
    fromAmountUsd: 355,
    toAmountUsd: 352.1,
    status: 'cancelled',
    provider: 'Trader Joe',
    createdAt: daysAgo(5),
  },
]

// Wrapper for interactive filter state
function InteractiveWrapper({
  entries,
  initialChainFilter = 'all',
  initialStatusFilter = 'all',
  ...rest
}: SwapHistoryProps & { initialChainFilter?: ChainFilter; initialStatusFilter?: StatusFilter }) {
  const [chainFilter, setChainFilter] = useState<ChainFilter>(initialChainFilter)
  const [statusFilter, setStatusFilter] = useState<StatusFilter>(initialStatusFilter)

  return (
    <SwapHistory
      {...rest}
      entries={entries}
      chainFilter={chainFilter}
      statusFilter={statusFilter}
      onChainFilterChange={setChainFilter}
      onStatusFilterChange={setStatusFilter}
    />
  )
}

// --- Stories ---

export const FullHistory: Story = {
  render: () => <InteractiveWrapper entries={mockEntries} />,
  args: { entries: mockEntries },
}

export const AllCompleted: Story = {
  render: () => (
    <InteractiveWrapper
      entries={mockEntries.filter((e) => e.status === 'completed')}
    />
  ),
  args: { entries: mockEntries.filter((e) => e.status === 'completed') },
}

export const WithPending: Story = {
  render: () => (
    <InteractiveWrapper
      entries={mockEntries.filter((e) => e.status === 'completed' || e.status === 'pending')}
    />
  ),
  args: { entries: mockEntries.filter((e) => e.status === 'completed' || e.status === 'pending') },
}

export const FilteredByChain: Story = {
  render: () => (
    <InteractiveWrapper entries={mockEntries} initialChainFilter="ethereum" />
  ),
  args: { entries: mockEntries, chainFilter: 'ethereum' },
}

export const FilteredByStatus: Story = {
  render: () => (
    <InteractiveWrapper entries={mockEntries} initialStatusFilter="failed" />
  ),
  args: { entries: mockEntries, statusFilter: 'failed' },
}

export const ExpandedEntry: Story = {
  render: () => {
    // Using a custom wrapper that auto-expands the first entry
    const AutoExpandWrapper = () => {
      return (
        <div>
          <p className="text-xs text-gray-400 mb-2">Click &quot;Expand&quot; on any entry to see details</p>
          <InteractiveWrapper entries={mockEntries.slice(0, 3)} />
        </div>
      )
    }
    return <AutoExpandWrapper />
  },
  args: { entries: mockEntries.slice(0, 3) },
}

export const EmptyState: Story = {
  args: {
    entries: [],
  },
}

export const EmptyFilter: Story = {
  render: () => (
    <InteractiveWrapper
      entries={mockEntries.filter((e) => e.status === 'completed')}
      initialStatusFilter="failed"
    />
  ),
  args: {
    entries: mockEntries.filter((e) => e.status === 'completed'),
    statusFilter: 'failed',
  },
}

export const Loading: Story = {
  args: {
    entries: [],
    isLoading: true,
  },
}

export const MobileViewport: Story = {
  render: () => (
    <div className="max-w-[360px] mx-auto">
      <InteractiveWrapper entries={mockEntries} />
    </div>
  ),
  args: { entries: mockEntries },
}

// --- New Story Data ---

const minutesAgo = (m: number) => new Date(now - m * 60_000).toISOString()

const profitableWeekEntries: SwapHistoryEntry[] = [
  {
    id: 'pw-1',
    fromToken: { symbol: 'USDC' },
    toToken: { symbol: 'ETH' },
    fromChain: 'ethereum',
    toChain: 'ethereum',
    fromAmount: 2000,
    toAmount: 1.62,
    fromAmountUsd: 2000,
    toAmountUsd: 2085.5,
    status: 'completed',
    provider: 'CoW Protocol',
    txHash: '0xpw1aaa111222333444555666777888999000aaabbbcccdddeeefffggg111222',
    explorerUrl: 'https://etherscan.io/tx/0xpw1aaa',
    pnl: 85.5,
    pnlPercent: 4.28,
    createdAt: daysAgo(1),
    completedAt: new Date(new Date(daysAgo(1)).getTime() + 15000).toISOString(),
  },
  {
    id: 'pw-2',
    fromToken: { symbol: 'ETH' },
    toToken: { symbol: 'ARB' },
    fromChain: 'arbitrum',
    toChain: 'arbitrum',
    fromAmount: 0.8,
    toAmount: 890.2,
    fromAmountUsd: 1028,
    toAmountUsd: 1069.44,
    status: 'completed',
    provider: 'Uniswap V3',
    txHash: '0xpw2bbb111222333444555666777888999000aaabbbcccdddeeefffggg222333',
    explorerUrl: 'https://arbiscan.io/tx/0xpw2bbb',
    pnl: 41.44,
    pnlPercent: 4.03,
    createdAt: daysAgo(2),
    completedAt: new Date(new Date(daysAgo(2)).getTime() + 8000).toISOString(),
  },
  {
    id: 'pw-3',
    fromToken: { symbol: 'SOL' },
    toToken: { symbol: 'JUP' },
    fromChain: 'solana',
    toChain: 'solana',
    fromAmount: 15,
    toAmount: 2850,
    fromAmountUsd: 2100,
    toAmountUsd: 2193,
    status: 'completed',
    provider: 'Jupiter',
    txHash: '4mKzPW1LGuxhFfVwRR9kzTnD...',
    explorerUrl: 'https://solscan.io/tx/4mKzPW1',
    pnl: 93,
    pnlPercent: 4.43,
    createdAt: daysAgo(3),
    completedAt: new Date(new Date(daysAgo(3)).getTime() + 2000).toISOString(),
  },
  {
    id: 'pw-4',
    fromToken: { symbol: 'USDT' },
    toToken: { symbol: 'OP' },
    fromChain: 'optimism',
    toChain: 'optimism',
    fromAmount: 1500,
    toAmount: 1020.4,
    fromAmountUsd: 1500,
    toAmountUsd: 1551.01,
    status: 'completed',
    provider: 'Velodrome',
    txHash: '0xpw4ddd111222333444555666777888999000aaabbbcccdddeeefffggg444555',
    explorerUrl: 'https://optimistic.etherscan.io/tx/0xpw4ddd',
    pnl: 51.01,
    pnlPercent: 3.4,
    createdAt: daysAgo(4),
    completedAt: new Date(new Date(daysAgo(4)).getTime() + 10000).toISOString(),
  },
  {
    id: 'pw-5',
    fromToken: { symbol: 'AVAX' },
    toToken: { symbol: 'USDC' },
    fromChain: 'avalanche',
    toChain: 'avalanche',
    fromAmount: 50,
    toAmount: 1830.25,
    fromAmountUsd: 1775,
    toAmountUsd: 1830.25,
    status: 'completed',
    provider: 'Trader Joe',
    txHash: '0xpw5eee111222333444555666777888999000aaabbbcccdddeeefffggg555666',
    explorerUrl: 'https://snowtrace.io/tx/0xpw5eee',
    pnl: 55.25,
    pnlPercent: 3.11,
    createdAt: daysAgo(5),
    completedAt: new Date(new Date(daysAgo(5)).getTime() + 6000).toISOString(),
  },
  {
    id: 'pw-6',
    fromToken: { symbol: 'WETH' },
    toToken: { symbol: 'AERO' },
    fromChain: 'base',
    toChain: 'base',
    fromAmount: 1.2,
    toAmount: 1450.8,
    fromAmountUsd: 1536,
    toAmountUsd: 1610.39,
    status: 'completed',
    provider: 'Aerodrome',
    txHash: '0xpw6fff111222333444555666777888999000aaabbbcccdddeeefffggg666777',
    explorerUrl: 'https://basescan.org/tx/0xpw6fff',
    pnl: 74.39,
    pnlPercent: 4.84,
    createdAt: daysAgo(6),
    completedAt: new Date(new Date(daysAgo(6)).getTime() + 9000).toISOString(),
  },
]

const badDayEntries: SwapHistoryEntry[] = [
  {
    id: 'bd-1',
    fromToken: { symbol: 'ETH' },
    toToken: { symbol: 'LINK' },
    fromChain: 'ethereum',
    toChain: 'ethereum',
    fromAmount: 1.5,
    toAmount: 128.4,
    fromAmountUsd: 1920,
    toAmountUsd: 1793.6,
    status: 'completed',
    provider: 'Uniswap V3',
    txHash: '0xbd1aaa111222333444555666777888999000aaabbbcccdddeeefffggg111222',
    explorerUrl: 'https://etherscan.io/tx/0xbd1aaa',
    pnl: -126.4,
    pnlPercent: -6.58,
    createdAt: hoursAgo(3),
    completedAt: hoursAgo(2.99),
  },
  {
    id: 'bd-2',
    fromToken: { symbol: 'USDC' },
    toToken: { symbol: 'AVAX' },
    fromChain: 'avalanche',
    toChain: 'avalanche',
    fromAmount: 3000,
    toAmount: 88.2,
    fromAmountUsd: 3000,
    toAmountUsd: 0,
    status: 'failed',
    provider: 'Trader Joe',
    txHash: '0xbd2bbb111222333444555666777888999000aaabbbcccdddeeefffggg222333',
    explorerUrl: 'https://snowtrace.io/tx/0xbd2bbb',
    createdAt: hoursAgo(5),
  },
  {
    id: 'bd-3',
    fromToken: { symbol: 'ARB' },
    toToken: { symbol: 'USDT' },
    fromChain: 'arbitrum',
    toChain: 'arbitrum',
    fromAmount: 2200,
    toAmount: 2420,
    fromAmountUsd: 2640,
    toAmountUsd: 2420,
    status: 'completed',
    provider: 'Uniswap V3',
    txHash: '0xbd3ccc111222333444555666777888999000aaabbbcccdddeeefffggg333444',
    explorerUrl: 'https://arbiscan.io/tx/0xbd3ccc',
    pnl: -220,
    pnlPercent: -8.33,
    createdAt: hoursAgo(7),
    completedAt: hoursAgo(6.99),
  },
  {
    id: 'bd-4',
    fromToken: { symbol: 'SOL' },
    toToken: { symbol: 'USDC' },
    fromChain: 'solana',
    toChain: 'solana',
    fromAmount: 10,
    toAmount: 0,
    fromAmountUsd: 1400,
    toAmountUsd: 0,
    status: 'failed',
    provider: 'Jupiter',
    txHash: '3xFailTxSolana...',
    explorerUrl: 'https://solscan.io/tx/3xFail',
    createdAt: hoursAgo(9),
  },
]

const crossChainHeavyEntries: SwapHistoryEntry[] = [
  {
    id: 'cc-1',
    fromToken: { symbol: 'ETH' },
    toToken: { symbol: 'USDC' },
    fromChain: 'ethereum',
    toChain: 'arbitrum',
    fromAmount: 2.0,
    toAmount: 2565.8,
    fromAmountUsd: 2560,
    toAmountUsd: 2565.8,
    status: 'completed',
    provider: 'Across',
    txHash: '0xcc1aaa111222333444555666777888999000aaabbbcccdddeeefffggg111222',
    explorerUrl: 'https://etherscan.io/tx/0xcc1aaa',
    pnl: 5.8,
    pnlPercent: 0.23,
    createdAt: hoursAgo(1),
    completedAt: hoursAgo(0.95),
  },
  {
    id: 'cc-2',
    fromToken: { symbol: 'USDC' },
    toToken: { symbol: 'USDC' },
    fromChain: 'arbitrum',
    toChain: 'base',
    fromAmount: 5000,
    toAmount: 4998.5,
    fromAmountUsd: 5000,
    toAmountUsd: 4998.5,
    status: 'completed',
    provider: 'cctp',
    txHash: '0xcc2bbb111222333444555666777888999000aaabbbcccdddeeefffggg222333',
    explorerUrl: 'https://arbiscan.io/tx/0xcc2bbb',
    pnl: -1.5,
    pnlPercent: -0.03,
    createdAt: hoursAgo(4),
    completedAt: hoursAgo(3.85),
  },
  {
    id: 'cc-3',
    fromToken: { symbol: 'SOL' },
    toToken: { symbol: 'ETH' },
    fromChain: 'solana',
    toChain: 'ethereum',
    fromAmount: 20,
    toAmount: 2.18,
    fromAmountUsd: 2800,
    toAmountUsd: 2794.24,
    status: 'completed',
    provider: 'wormhole',
    txHash: '7bWormholeBridge...',
    explorerUrl: 'https://solscan.io/tx/7bWormhole',
    pnl: -5.76,
    pnlPercent: -0.21,
    createdAt: hoursAgo(8),
    completedAt: hoursAgo(7.7),
  },
  {
    id: 'cc-4',
    fromToken: { symbol: 'MATIC' },
    toToken: { symbol: 'USDC' },
    fromChain: 'polygon',
    toChain: 'optimism',
    fromAmount: 3000,
    toAmount: 2547.3,
    fromAmountUsd: 2550,
    toAmountUsd: 2547.3,
    status: 'pending',
    provider: 'Across',
    txHash: '0xcc4ddd111222333444555666777888999000aaabbbcccdddeeefffggg444555',
    createdAt: hoursAgo(0.05),
  },
  {
    id: 'cc-5',
    fromToken: { symbol: 'AVAX' },
    toToken: { symbol: 'BNB' },
    fromChain: 'avalanche',
    toChain: 'bsc',
    fromAmount: 100,
    toAmount: 5.92,
    fromAmountUsd: 3550,
    toAmountUsd: 3562.24,
    status: 'completed',
    provider: 'wormhole',
    txHash: '0xcc5eee111222333444555666777888999000aaabbbcccdddeeefffggg555666',
    explorerUrl: 'https://snowtrace.io/tx/0xcc5eee',
    pnl: 12.24,
    pnlPercent: 0.34,
    createdAt: hoursAgo(12),
    completedAt: hoursAgo(11.75),
  },
]

const memeTradingEntries: SwapHistoryEntry[] = [
  {
    id: 'mt-1',
    fromToken: { symbol: 'ETH' },
    toToken: { symbol: 'PEPE' },
    fromChain: 'ethereum',
    toChain: 'ethereum',
    fromAmount: 0.5,
    toAmount: 52_000_000_000,
    fromAmountUsd: 640,
    toAmountUsd: 780.8,
    status: 'completed',
    provider: 'Uniswap V3',
    txHash: '0xmt1aaa111222333444555666777888999000aaabbbcccdddeeefffggg111222',
    explorerUrl: 'https://etherscan.io/tx/0xmt1aaa',
    pnl: 140.8,
    pnlPercent: 22.0,
    createdAt: hoursAgo(2),
    completedAt: hoursAgo(1.99),
  },
  {
    id: 'mt-2',
    fromToken: { symbol: 'USDC' },
    toToken: { symbol: 'SHIB' },
    fromChain: 'ethereum',
    toChain: 'ethereum',
    fromAmount: 1000,
    toAmount: 62_500_000_000,
    fromAmountUsd: 1000,
    toAmountUsd: 812.5,
    status: 'completed',
    provider: 'CoW Protocol',
    txHash: '0xmt2bbb111222333444555666777888999000aaabbbcccdddeeefffggg222333',
    explorerUrl: 'https://etherscan.io/tx/0xmt2bbb',
    pnl: -187.5,
    pnlPercent: -18.75,
    createdAt: hoursAgo(6),
    completedAt: hoursAgo(5.99),
  },
  {
    id: 'mt-3',
    fromToken: { symbol: 'USDC' },
    toToken: { symbol: 'DOGE' },
    fromChain: 'bsc',
    toChain: 'bsc',
    fromAmount: 500,
    toAmount: 2840.9,
    fromAmountUsd: 500,
    toAmountUsd: 568.18,
    status: 'completed',
    provider: 'PancakeSwap',
    txHash: '0xmt3ccc111222333444555666777888999000aaabbbcccdddeeefffggg333444',
    explorerUrl: 'https://bscscan.com/tx/0xmt3ccc',
    pnl: 68.18,
    pnlPercent: 13.64,
    createdAt: hoursAgo(10),
    completedAt: hoursAgo(9.99),
  },
  {
    id: 'mt-4',
    fromToken: { symbol: 'SOL' },
    toToken: { symbol: 'BONK' },
    fromChain: 'solana',
    toChain: 'solana',
    fromAmount: 5,
    toAmount: 24_500_000,
    fromAmountUsd: 700,
    toAmountUsd: 490,
    status: 'completed',
    provider: 'Jupiter',
    txHash: '9mBonkTrade...',
    explorerUrl: 'https://solscan.io/tx/9mBonk',
    pnl: -210,
    pnlPercent: -30.0,
    createdAt: hoursAgo(14),
    completedAt: hoursAgo(13.99),
  },
  {
    id: 'mt-5',
    fromToken: { symbol: 'PEPE' },
    toToken: { symbol: 'ETH' },
    fromChain: 'ethereum',
    toChain: 'ethereum',
    fromAmount: 100_000_000_000,
    toAmount: 1.18,
    fromAmountUsd: 1500,
    toAmountUsd: 1512.96,
    status: 'completed',
    provider: 'Uniswap V3',
    txHash: '0xmt5eee111222333444555666777888999000aaabbbcccdddeeefffggg555666',
    explorerUrl: 'https://etherscan.io/tx/0xmt5eee',
    pnl: 12.96,
    pnlPercent: 0.86,
    createdAt: hoursAgo(20),
    completedAt: hoursAgo(19.99),
  },
]

const whaleActivityEntries: SwapHistoryEntry[] = [
  {
    id: 'wh-1',
    fromToken: { symbol: 'USDC' },
    toToken: { symbol: 'ETH' },
    fromChain: 'ethereum',
    toChain: 'ethereum',
    fromAmount: 250_000,
    toAmount: 195.31,
    fromAmountUsd: 250_000,
    toAmountUsd: 250_400,
    status: 'completed',
    provider: 'CoW Protocol',
    txHash: '0xwh1aaa111222333444555666777888999000aaabbbcccdddeeefffggg111222',
    explorerUrl: 'https://etherscan.io/tx/0xwh1aaa',
    pnl: 400,
    pnlPercent: 0.16,
    createdAt: hoursAgo(3),
    completedAt: hoursAgo(2.98),
  },
  {
    id: 'wh-2',
    fromToken: { symbol: 'ETH' },
    toToken: { symbol: 'USDT' },
    fromChain: 'ethereum',
    toChain: 'arbitrum',
    fromAmount: 120,
    toAmount: 153_360,
    fromAmountUsd: 153_600,
    toAmountUsd: 153_360,
    status: 'completed',
    provider: 'Across',
    txHash: '0xwh2bbb111222333444555666777888999000aaabbbcccdddeeefffggg222333',
    explorerUrl: 'https://etherscan.io/tx/0xwh2bbb',
    pnl: -240,
    pnlPercent: -0.16,
    createdAt: daysAgo(1),
    completedAt: new Date(new Date(daysAgo(1)).getTime() + 25000).toISOString(),
  },
  {
    id: 'wh-3',
    fromToken: { symbol: 'WBTC' },
    toToken: { symbol: 'USDC' },
    fromChain: 'ethereum',
    toChain: 'ethereum',
    fromAmount: 5.0,
    toAmount: 510_250,
    fromAmountUsd: 510_000,
    toAmountUsd: 510_250,
    status: 'completed',
    provider: 'CoW Protocol',
    txHash: '0xwh3ccc111222333444555666777888999000aaabbbcccdddeeefffggg333444',
    explorerUrl: 'https://etherscan.io/tx/0xwh3ccc',
    pnl: 250,
    pnlPercent: 0.05,
    createdAt: daysAgo(2),
    completedAt: new Date(new Date(daysAgo(2)).getTime() + 18000).toISOString(),
  },
]

const solanaOnlyEntries: SwapHistoryEntry[] = [
  {
    id: 'sol-1',
    fromToken: { symbol: 'SOL' },
    toToken: { symbol: 'USDC' },
    fromChain: 'solana',
    toChain: 'solana',
    fromAmount: 10,
    toAmount: 1400,
    fromAmountUsd: 1400,
    toAmountUsd: 1400,
    status: 'completed',
    provider: 'Jupiter',
    txHash: '2xSolSwap1ABCDE...',
    explorerUrl: 'https://solscan.io/tx/2xSolSwap1',
    pnl: 0,
    pnlPercent: 0,
    createdAt: hoursAgo(1),
    completedAt: new Date(new Date(hoursAgo(1)).getTime() + 800).toISOString(),
  },
  {
    id: 'sol-2',
    fromToken: { symbol: 'USDC' },
    toToken: { symbol: 'JUP' },
    fromChain: 'solana',
    toChain: 'solana',
    fromAmount: 500,
    toAmount: 650.2,
    fromAmountUsd: 500,
    toAmountUsd: 520.16,
    status: 'completed',
    provider: 'Jupiter',
    txHash: '5kJupBuy2FGHIJ...',
    explorerUrl: 'https://solscan.io/tx/5kJupBuy2',
    pnl: 20.16,
    pnlPercent: 4.03,
    createdAt: hoursAgo(3),
    completedAt: new Date(new Date(hoursAgo(3)).getTime() + 650).toISOString(),
  },
  {
    id: 'sol-3',
    fromToken: { symbol: 'SOL' },
    toToken: { symbol: 'BONK' },
    fromChain: 'solana',
    toChain: 'solana',
    fromAmount: 2,
    toAmount: 6_800_000,
    fromAmountUsd: 280,
    toAmountUsd: 272,
    status: 'completed',
    provider: 'Jupiter',
    txHash: '8rBonkSwap3KLM...',
    explorerUrl: 'https://solscan.io/tx/8rBonkSwap3',
    pnl: -8,
    pnlPercent: -2.86,
    createdAt: hoursAgo(5),
    completedAt: new Date(new Date(hoursAgo(5)).getTime() + 900).toISOString(),
  },
  {
    id: 'sol-4',
    fromToken: { symbol: 'JUP' },
    toToken: { symbol: 'SOL' },
    fromChain: 'solana',
    toChain: 'solana',
    fromAmount: 1200,
    toAmount: 6.48,
    fromAmountUsd: 960,
    toAmountUsd: 907.2,
    status: 'completed',
    provider: 'Jupiter',
    txHash: '3nJupSell4NOP...',
    explorerUrl: 'https://solscan.io/tx/3nJupSell4',
    pnl: -52.8,
    pnlPercent: -5.5,
    createdAt: hoursAgo(8),
    completedAt: new Date(new Date(hoursAgo(8)).getTime() + 720).toISOString(),
  },
  {
    id: 'sol-5',
    fromToken: { symbol: 'USDC' },
    toToken: { symbol: 'RAY' },
    fromChain: 'solana',
    toChain: 'solana',
    fromAmount: 300,
    toAmount: 152.3,
    fromAmountUsd: 300,
    toAmountUsd: 318.81,
    status: 'completed',
    provider: 'Jupiter',
    txHash: '6wRayBuy5QRS...',
    explorerUrl: 'https://solscan.io/tx/6wRayBuy5',
    pnl: 18.81,
    pnlPercent: 6.27,
    createdAt: hoursAgo(12),
    completedAt: new Date(new Date(hoursAgo(12)).getTime() + 550).toISOString(),
  },
]

const denseTimelineEntries: SwapHistoryEntry[] = Array.from({ length: 12 }, (_, i) => {
  const tokens = [
    { from: 'ETH', to: 'USDC', chain: 'ethereum', provider: 'Uniswap V3' },
    { from: 'USDC', to: 'ARB', chain: 'arbitrum', provider: 'Uniswap V3' },
    { from: 'WETH', to: 'DAI', chain: 'base', provider: 'Aerodrome' },
    { from: 'SOL', to: 'USDC', chain: 'solana', provider: 'Jupiter' },
    { from: 'MATIC', to: 'USDT', chain: 'polygon', provider: 'QuickSwap' },
    { from: 'OP', to: 'ETH', chain: 'optimism', provider: 'Velodrome' },
    { from: 'USDC', to: 'WETH', chain: 'base', provider: 'Aerodrome' },
    { from: 'ETH', to: 'LINK', chain: 'ethereum', provider: 'CoW Protocol' },
    { from: 'USDT', to: 'AVAX', chain: 'avalanche', provider: 'Trader Joe' },
    { from: 'ARB', to: 'USDC', chain: 'arbitrum', provider: 'Uniswap V3' },
    { from: 'USDC', to: 'SOL', chain: 'solana', provider: 'Jupiter' },
    { from: 'DAI', to: 'ETH', chain: 'ethereum', provider: 'CoW Protocol' },
  ]
  const t = tokens[i]
  const pnlVal = (Math.sin(i * 1.7) * 15).toFixed(2)
  const pnlNum = parseFloat(pnlVal)
  const baseUsd = 200 + i * 80
  return {
    id: `dt-${i + 1}`,
    fromToken: { symbol: t.from },
    toToken: { symbol: t.to },
    fromChain: t.chain,
    toChain: t.chain,
    fromAmount: baseUsd / (50 + i * 10),
    toAmount: (baseUsd + pnlNum) / (30 + i * 5),
    fromAmountUsd: baseUsd,
    toAmountUsd: baseUsd + pnlNum,
    status: 'completed' as const,
    provider: t.provider,
    txHash: `0xdt${i + 1}hash${String(i).padStart(4, '0')}...`,
    explorerUrl: `https://etherscan.io/tx/0xdt${i + 1}`,
    pnl: pnlNum,
    pnlPercent: (pnlNum / baseUsd) * 100,
    createdAt: minutesAgo(5 * (12 - i)),
    completedAt: minutesAgo(5 * (12 - i) - 0.3),
  }
})

const longHistoryEntries: SwapHistoryEntry[] = [
  // Week 1 (recent)
  {
    id: 'lh-1',
    fromToken: { symbol: 'ETH' },
    toToken: { symbol: 'USDC' },
    fromChain: 'ethereum',
    toChain: 'ethereum',
    fromAmount: 0.5,
    toAmount: 640.5,
    fromAmountUsd: 640,
    toAmountUsd: 640.5,
    status: 'completed',
    provider: 'CoW Protocol',
    txHash: '0xlh01aa...',
    explorerUrl: 'https://etherscan.io/tx/0xlh01',
    pnl: 0.5,
    pnlPercent: 0.08,
    createdAt: hoursAgo(2),
    completedAt: hoursAgo(1.99),
  },
  {
    id: 'lh-2',
    fromToken: { symbol: 'USDC' },
    toToken: { symbol: 'ARB' },
    fromChain: 'arbitrum',
    toChain: 'arbitrum',
    fromAmount: 800,
    toAmount: 680,
    fromAmountUsd: 800,
    toAmountUsd: 816,
    status: 'completed',
    provider: 'Uniswap V3',
    txHash: '0xlh02bb...',
    explorerUrl: 'https://arbiscan.io/tx/0xlh02',
    pnl: 16,
    pnlPercent: 2.0,
    createdAt: hoursAgo(8),
    completedAt: hoursAgo(7.99),
  },
  {
    id: 'lh-3',
    fromToken: { symbol: 'SOL' },
    toToken: { symbol: 'USDC' },
    fromChain: 'solana',
    toChain: 'solana',
    fromAmount: 4,
    toAmount: 556,
    fromAmountUsd: 560,
    toAmountUsd: 556,
    status: 'completed',
    provider: 'Jupiter',
    txHash: '4xLhSol03...',
    explorerUrl: 'https://solscan.io/tx/4xLhSol03',
    pnl: -4,
    pnlPercent: -0.71,
    createdAt: daysAgo(1),
    completedAt: new Date(new Date(daysAgo(1)).getTime() + 1500).toISOString(),
  },
  {
    id: 'lh-4',
    fromToken: { symbol: 'WETH' },
    toToken: { symbol: 'AERO' },
    fromChain: 'base',
    toChain: 'base',
    fromAmount: 0.3,
    toAmount: 380,
    fromAmountUsd: 384,
    toAmountUsd: 399.38,
    status: 'completed',
    provider: 'Aerodrome',
    txHash: '0xlh04dd...',
    explorerUrl: 'https://basescan.org/tx/0xlh04',
    pnl: 15.38,
    pnlPercent: 4.0,
    createdAt: daysAgo(2),
    completedAt: new Date(new Date(daysAgo(2)).getTime() + 7000).toISOString(),
  },
  // Week 2
  {
    id: 'lh-5',
    fromToken: { symbol: 'MATIC' },
    toToken: { symbol: 'USDT' },
    fromChain: 'polygon',
    toChain: 'polygon',
    fromAmount: 2000,
    toAmount: 1700,
    fromAmountUsd: 1700,
    toAmountUsd: 1700,
    status: 'completed',
    provider: 'QuickSwap',
    txHash: '0xlh05ee...',
    explorerUrl: 'https://polygonscan.com/tx/0xlh05',
    pnl: 0,
    pnlPercent: 0,
    createdAt: daysAgo(4),
    completedAt: new Date(new Date(daysAgo(4)).getTime() + 5000).toISOString(),
  },
  {
    id: 'lh-6',
    fromToken: { symbol: 'ETH' },
    toToken: { symbol: 'OP' },
    fromChain: 'optimism',
    toChain: 'optimism',
    fromAmount: 0.8,
    toAmount: 560,
    fromAmountUsd: 1024,
    toAmountUsd: 1008.64,
    status: 'completed',
    provider: 'Velodrome',
    txHash: '0xlh06ff...',
    explorerUrl: 'https://optimistic.etherscan.io/tx/0xlh06',
    pnl: -15.36,
    pnlPercent: -1.5,
    createdAt: daysAgo(5),
    completedAt: new Date(new Date(daysAgo(5)).getTime() + 11000).toISOString(),
  },
  {
    id: 'lh-7',
    fromToken: { symbol: 'AVAX' },
    toToken: { symbol: 'USDC' },
    fromChain: 'avalanche',
    toChain: 'avalanche',
    fromAmount: 25,
    toAmount: 887.5,
    fromAmountUsd: 887.5,
    toAmountUsd: 887.5,
    status: 'cancelled',
    provider: 'Trader Joe',
    createdAt: daysAgo(6),
  },
  {
    id: 'lh-8',
    fromToken: { symbol: 'BNB' },
    toToken: { symbol: 'USDT' },
    fromChain: 'bsc',
    toChain: 'bsc',
    fromAmount: 3,
    toAmount: 1806,
    fromAmountUsd: 1800,
    toAmountUsd: 1806,
    status: 'completed',
    provider: 'PancakeSwap',
    txHash: '0xlh08hh...',
    explorerUrl: 'https://bscscan.com/tx/0xlh08',
    pnl: 6,
    pnlPercent: 0.33,
    createdAt: daysAgo(7),
    completedAt: new Date(new Date(daysAgo(7)).getTime() + 4000).toISOString(),
  },
  // Week 3
  {
    id: 'lh-9',
    fromToken: { symbol: 'ETH' },
    toToken: { symbol: 'USDC' },
    fromChain: 'ethereum',
    toChain: 'arbitrum',
    fromAmount: 1.5,
    toAmount: 1920,
    fromAmountUsd: 1920,
    toAmountUsd: 1920,
    status: 'completed',
    provider: 'Across',
    txHash: '0xlh09ii...',
    explorerUrl: 'https://etherscan.io/tx/0xlh09',
    pnl: 0,
    pnlPercent: 0,
    createdAt: daysAgo(9),
    completedAt: new Date(new Date(daysAgo(9)).getTime() + 20000).toISOString(),
  },
  {
    id: 'lh-10',
    fromToken: { symbol: 'USDC' },
    toToken: { symbol: 'SOL' },
    fromChain: 'solana',
    toChain: 'solana',
    fromAmount: 700,
    toAmount: 5.0,
    fromAmountUsd: 700,
    toAmountUsd: 700,
    status: 'failed',
    provider: 'Jupiter',
    txHash: '6qFailSol10...',
    explorerUrl: 'https://solscan.io/tx/6qFail',
    createdAt: daysAgo(10),
  },
  {
    id: 'lh-11',
    fromToken: { symbol: 'LINK' },
    toToken: { symbol: 'ETH' },
    fromChain: 'ethereum',
    toChain: 'ethereum',
    fromAmount: 100,
    toAmount: 0.98,
    fromAmountUsd: 1400,
    toAmountUsd: 1254.4,
    status: 'completed',
    provider: 'Uniswap V3',
    txHash: '0xlh11kk...',
    explorerUrl: 'https://etherscan.io/tx/0xlh11',
    pnl: -145.6,
    pnlPercent: -10.4,
    createdAt: daysAgo(12),
    completedAt: new Date(new Date(daysAgo(12)).getTime() + 14000).toISOString(),
  },
  {
    id: 'lh-12',
    fromToken: { symbol: 'WETH' },
    toToken: { symbol: 'DAI' },
    fromChain: 'base',
    toChain: 'base',
    fromAmount: 0.2,
    toAmount: 258.4,
    fromAmountUsd: 256,
    toAmountUsd: 258.4,
    status: 'completed',
    provider: 'Aerodrome',
    txHash: '0xlh12ll...',
    explorerUrl: 'https://basescan.org/tx/0xlh12',
    pnl: 2.4,
    pnlPercent: 0.94,
    createdAt: daysAgo(14),
    completedAt: new Date(new Date(daysAgo(14)).getTime() + 8000).toISOString(),
  },
  // Week 4+
  {
    id: 'lh-13',
    fromToken: { symbol: 'ARB' },
    toToken: { symbol: 'ETH' },
    fromChain: 'arbitrum',
    toChain: 'arbitrum',
    fromAmount: 500,
    toAmount: 0.47,
    fromAmountUsd: 600,
    toAmountUsd: 602.24,
    status: 'completed',
    provider: 'Uniswap V3',
    txHash: '0xlh13mm...',
    explorerUrl: 'https://arbiscan.io/tx/0xlh13',
    pnl: 2.24,
    pnlPercent: 0.37,
    createdAt: daysAgo(17),
    completedAt: new Date(new Date(daysAgo(17)).getTime() + 6000).toISOString(),
  },
  {
    id: 'lh-14',
    fromToken: { symbol: 'ETH' },
    toToken: { symbol: 'USDC' },
    fromChain: 'ethereum',
    toChain: 'ethereum',
    fromAmount: 2.0,
    toAmount: 2564,
    fromAmountUsd: 2560,
    toAmountUsd: 2564,
    status: 'completed',
    provider: 'CoW Protocol',
    txHash: '0xlh14nn...',
    explorerUrl: 'https://etherscan.io/tx/0xlh14',
    pnl: 4,
    pnlPercent: 0.16,
    createdAt: daysAgo(20),
    completedAt: new Date(new Date(daysAgo(20)).getTime() + 16000).toISOString(),
  },
  {
    id: 'lh-15',
    fromToken: { symbol: 'SOL' },
    toToken: { symbol: 'BONK' },
    fromChain: 'solana',
    toChain: 'solana',
    fromAmount: 8,
    toAmount: 28_000_000,
    fromAmountUsd: 1120,
    toAmountUsd: 1064,
    status: 'completed',
    provider: 'Jupiter',
    txHash: '9pBonkOld15...',
    explorerUrl: 'https://solscan.io/tx/9pBonkOld15',
    pnl: -56,
    pnlPercent: -5.0,
    createdAt: daysAgo(24),
    completedAt: new Date(new Date(daysAgo(24)).getTime() + 1200).toISOString(),
  },
  {
    id: 'lh-16',
    fromToken: { symbol: 'USDT' },
    toToken: { symbol: 'ETH' },
    fromChain: 'ethereum',
    toChain: 'ethereum',
    fromAmount: 5000,
    toAmount: 3.92,
    fromAmountUsd: 5000,
    toAmountUsd: 5019.2,
    status: 'completed',
    provider: 'CoW Protocol',
    txHash: '0xlh16pp...',
    explorerUrl: 'https://etherscan.io/tx/0xlh16',
    pnl: 19.2,
    pnlPercent: 0.38,
    createdAt: daysAgo(28),
    completedAt: new Date(new Date(daysAgo(28)).getTime() + 13000).toISOString(),
  },
]

// --- New Stories ---

export const ProfitableWeek: Story = {
  args: {} as any,
  render: () => <InteractiveWrapper entries={profitableWeekEntries} />,
}

export const BadDay: Story = {
  args: {} as any,
  render: () => <InteractiveWrapper entries={badDayEntries} />,
}

export const CrossChainHeavy: Story = {
  args: {} as any,
  render: () => <InteractiveWrapper entries={crossChainHeavyEntries} />,
}

export const MemeTrading: Story = {
  args: {} as any,
  render: () => <InteractiveWrapper entries={memeTradingEntries} />,
}

export const WhaleActivity: Story = {
  args: {} as any,
  render: () => <InteractiveWrapper entries={whaleActivityEntries} />,
}

export const SolanaOnly: Story = {
  args: {} as any,
  render: () => <InteractiveWrapper entries={solanaOnlyEntries} />,
}

export const DenseTimeline: Story = {
  args: {} as any,
  render: () => <InteractiveWrapper entries={denseTimelineEntries} />,
}

export const LongHistory: Story = {
  args: {} as any,
  render: () => <InteractiveWrapper entries={longHistoryEntries} />,
}
